/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Challenge } from "./types.js";

export const CHALLENGES: Challenge[] = [
  
 { scenario: "After three drinks, my dance move can only be described as _____.", category: "Dance Floor Disasters" },
{ scenario: "Scientists have discovered that the real cause of insomnia is _____.", category: "Junk Science" },
{ scenario: "My dating profile says I'm looking for someone who enjoys long walks and _____.", category: "Dating Disasters" },
{ scenario: "The new extreme sport sweeping the nation: _____.", category: "Extreme Nonsense" },
{ scenario: "What do pirates actually spend most of their time doing? _____.", category: "Historical Myths" },
{ scenario: "My Uber driver started the trip by telling me all about _____.", category: "Awkward Rides" },
{ scenario: "Scientists say the key to a long life is _____.", category: "Bad Advice" },
{ scenario: "The worst possible thing to accidentally say during a job interview: _____.", category: "Career Suicide" },
{ scenario: "I went to Vegas and lost everything, including _____.", category: "Vegas Stories" },
{ scenario: "My spirit animal is _____.", category: "Self Discovery" },
{ scenario: "When I die, I want my obituary to mention _____.", category: "Final Words" },
{ scenario: "The secret to making the perfect first impression is _____.", category: "Social Skills" },
{ scenario: "What's the weirdest thing about being a mermaid? _____.", category: "Fantasy Problems" },
{ scenario: "A new study shows that men think about _____ every seven seconds.", category: "Junk Science" },
{ scenario: "My gym trainer suggested I replace my warm-up routine with _____.", category: "Fitness Fails" },
{ scenario: "The doctor said I have a rare condition where I can't stop _____.", category: "Medical Mysteries" },
{ scenario: "In my will, I've left everything to my pet, except for _____.", category: "Final Words" },
{ scenario: "The new diet everyone is talking about involves only eating _____ for 30 days.", category: "Bad Advice" },
{ scenario: "I matched with someone on Tinder and the first thing they sent me was _____.", category: "Dating Disasters" },
{ scenario: "The worst thing to find in your hotel room: _____.", category: "Travel Nightmares" },
{ scenario: "Before the colonoscopy, my doctor casually mentioned _____.", category: "Medical Mysteries" },
{ scenario: "The ancient Egyptians were ahead of their time, having already invented _____.", category: "Historical Myths" },
{ scenario: "What really goes on in a medieval dungeon? _____.", category: "Historical Myths" },
{ scenario: "My roommate and I had our biggest fight over _____.", category: "Roommate Hell" },
{ scenario: "The police report simply described the incident as involving _____.", category: "Legal Trouble" },
{ scenario: "The one thing they never warn you about when moving to the countryside is _____.", category: "Rural Life" },
{ scenario: "My horoscope told me to avoid _____ this month, but I did it anyway.", category: "Cosmic Regrets" },
{ scenario: "The worst birthday gift I ever received was _____.", category: "Gift Giving Gone Wrong" },
{ scenario: "A zookeeper's most embarrassing moment involved _____.", category: "Animal Incidents" },
{ scenario: "What do clowns actually do when they go home after work? _____.", category: "Behind the Scenes" },
{ scenario: "My yoga instructor said the next pose was called _____.", category: "Fitness Fails" },
{ scenario: "The least relaxing spa treatment in existence: _____.", category: "Wellness Nonsense" },
{ scenario: "I tried to be romantic but things went south when I introduced _____.", category: "Romance Fails" },
{ scenario: "The new wellness trend Silicon Valley is obsessed with: _____.", category: "Wellness Nonsense" },
{ scenario: "On my gap year, I found myself in a small village where the locals worshipped _____.", category: "Travel Nightmares" },
{ scenario: "The last known words of the world's worst magician: _____.", category: "Dying Arts" },
{ scenario: "My food delivery arrived with a handwritten note that said _____.", category: "Delivery Drama" },
{ scenario: "The thing that finally convinced me to delete my social media was _____.", category: "Digital Detox" },
{ scenario: "The world's most niche museum is dedicated entirely to _____.", category: "Weird Attractions" },
{ scenario: "The most passive-aggressive thing you can put in a work email: _____.", category: "Office Life" },
{ scenario: "My dog's psychic had serious concerns about _____.", category: "Animal Incidents" },
{ scenario: "The most dangerous thing about competitive cheese rolling is _____.", category: "Extreme Nonsense" },
{ scenario: "My new fitness tracker has a setting specifically for _____.", category: "Tech Problems" },
{ scenario: "The haunted house had the usual stuff, but nobody was prepared for _____.", category: "Horror Fails" },
{ scenario: "The retirement speech no one expected ended with _____.", category: "Office Life" },
{ scenario: "Scientists confirmed that the dinosaurs were actually killed by _____.", category: "Junk Science" },
{ scenario: "The most romantic thing you can whisper in someone's ear: _____.", category: "Romance Fails" },
{ scenario: "What really happens at 3 AM in a nursing home? _____.", category: "Behind the Scenes" },
{ scenario: "The title of the world's worst self-help book: _____.", category: "Bad Advice" },
{ scenario: "My therapist broke her professional silence when I told her about _____.", category: "Shrunk Talk" },
{ scenario: "The country's most useless law involves a ban on _____.", category: "Legal Trouble" },
{ scenario: "My hairdresser won't stop talking about _____.", category: "Awkward Conversations" },
{ scenario: "The new flavour of Monster Energy Drink is called _____ and tastes like _____.", category: "Questionable Products" },
{ scenario: "The weirdest thing sold on eBay last week: _____.", category: "Weird Attractions" },
{ scenario: "My Airbnb host left a note saying I was not allowed to _____.", category: "Travel Nightmares" },
{ scenario: "The worst possible ringtone for a funeral director: _____.", category: "Dying Arts" },
{ scenario: "The one thing that will truly ruin a camping trip: _____.", category: "Outdoor Disasters" },
{ scenario: "Nature documentary voice: 'And here, we see the suburban human attempting _____.'", category: "Nature's Mistakes" },
{ scenario: "The new Olympic sport that nobody asked for: _____.", category: "Sports Disasters" },
{ scenario: "The least dignified way to be remembered in history: _____.", category: "Legacy Fails" },
{ scenario: "My blind date showed up carrying _____.", category: "Dating Disasters" },
{ scenario: "The world's most unnecessary invention: _____.", category: "Questionable Products" },
{ scenario: "The sign outside the small-town bar read: 'No _____ allowed.'", category: "Rural Life" },
{ scenario: "My dog was banned from the vet because of _____.", category: "Animal Incidents" },
{ scenario: "The worst Yelp review ever written was for a restaurant that served _____.", category: "Foodie Fails" },
{ scenario: "In hindsight, naming my boat _____ was a mistake.", category: "Bad Decisions" },
{ scenario: "The new Michelin-star chef is famous for his signature dish: _____.", category: "Foodie Fails" },
{ scenario: "The only thing weirder than the séance itself was _____.", category: "Supernatural Shenanigans" },
{ scenario: "My fortune cookie said: 'Beware of _____.'", category: "Cosmic Regrets" },
{ scenario: "The talent show went sideways when contestant number three performed _____.", category: "Performance Fails" },
{ scenario: "The strange thing about competitive eating isn't the food — it's _____.", category: "Sports Disasters" },
{ scenario: "What do flight attendants talk about when passengers aren't listening? _____.", category: "Behind the Scenes" },
{ scenario: "The cult had normal initiation rituals, except for _____.", category: "Supernatural Shenanigans" },
{ scenario: "The strangest thing about nudist colonies is not the nudity — it's _____.", category: "Lifestyle Choices" },
{ scenario: "The world record for the most _____ done simultaneously was broken last Tuesday.", category: "Weird Attractions" },
{ scenario: "The sommelier swirled the wine, sniffed it, and declared it tasted of _____.", category: "Foodie Fails" },
{ scenario: "I agreed to be the best man, not knowing I'd have to handle _____.", category: "Wedding Chaos" },
{ scenario: "The bride's vows were going well until she mentioned _____.", category: "Wedding Chaos" },
{ scenario: "The worst thing to accidentally send to your boss: _____.", category: "Office Life" },
{ scenario: "On my bucket list: experience _____ before I die.", category: "Final Words" },
{ scenario: "The gym's new class is called _____ and no one knows what to expect.", category: "Fitness Fails" },
{ scenario: "The dumbest way to break a world record: _____.", category: "Sports Disasters" },
{ scenario: "My neighbor's excuse for the noise at 2 AM was _____.", category: "Neighbor Nightmares" },
{ scenario: "The new luxury hotel amenity no one asked for: _____.", category: "Travel Nightmares" },
{ scenario: "My cat's therapist says she has unresolved issues with _____.", category: "Animal Incidents" },
{ scenario: "The most confusing warning label ever printed was found on _____.", category: "Questionable Products" },
{ scenario: "A man walks into a bar and says 'I'll have _____, please.' The bartender stares.", category: "Bar Jokes" },
{ scenario: "The conspiracy theorist's latest video claims that _____ is secretly controlled by lizard people.", category: "Conspiracy Theories" },
{ scenario: "What's the worst thing to stumble upon in the woods? _____.", category: "Outdoor Disasters" },
{ scenario: "My landlord's list of banned activities now includes _____.", category: "Rental Woes" },
{ scenario: "The least effective self-defense technique ever invented: _____.", category: "Bad Advice" },
{ scenario: "Scientists say that _____ is the new superpower no one talks about.", category: "Junk Science" },
{ scenario: "The cruise ship captain announced over the intercom: 'Please stop _____.'", category: "Travel Nightmares" },
{ scenario: "The mascot for the new sports team is a giant _____, and everyone hates it.", category: "Sports Disasters" },
{ scenario: "The midlife crisis hit differently when he bought _____ instead of a sports car.", category: "Life Stages" },
{ scenario: "My personal trainer is also certified in _____ which explains a lot.", category: "Fitness Fails" },
{ scenario: "The underground fight club has a strict rule: no _____.", category: "Rule Breakers" },
{ scenario: "What's the real reason cats knock things off tables? _____.", category: "Animal Incidents" },
{ scenario: "The new true crime podcast is about someone who got away with _____.", category: "True Crime Lite" },
{ scenario: "The worst possible thing to find at the bottom of a swimming pool: _____.", category: "Summer Fails" },
{ scenario: "The escape room's final puzzle involved _____.", category: "Entertainment Fails" },
{ scenario: "My dentist and I don't talk about anything other than _____.", category: "Awkward Conversations" },
{ scenario: "The office Secret Santa gifted someone _____ and HR got involved.", category: "Office Life" },
{ scenario: "The pirate's treasure chest was filled with nothing but _____.", category: "Historical Myths" },
{ scenario: "The world's worst life coach's signature advice: _____.", category: "Bad Advice" },
{ scenario: "The ghost didn't haunt the house, it just kept leaving _____ everywhere.", category: "Supernatural Shenanigans" },
{ scenario: "The smell coming from my neighbor's house turned out to be _____.", category: "Neighbor Nightmares" },
{ scenario: "The biggest red flag on a first date is when they order _____ to drink.", category: "Dating Disasters" },
{ scenario: "I got kicked out of a casino for _____.", category: "Vegas Stories" },
{ scenario: "The worst possible souvenir to bring back from a holiday: _____.", category: "Travel Nightmares" },
{ scenario: "What's really inside a hot dog? _____.", category: "Fast Food Secrets" },
{ scenario: "The winery's newest vintage is described as having notes of _____.", category: "Foodie Fails" },
{ scenario: "The last thing you want to hear from your Airbnb host is _____.", category: "Travel Nightmares" },
{ scenario: "My blind date's opening line was: 'I should tell you upfront, I have a thing for _____.'", category: "Dating Disasters" },
{ scenario: "The least dignified way to end a marathon: _____.", category: "Sports Disasters" },
{ scenario: "The autopsy report listed the cause of death as an acute overdose of _____.", category: "Medical Mysteries" },
{ scenario: "My accountant told me I could legally write off _____ as a business expense.", category: "Career Suicide" },
{ scenario: "The new employee was fired on their first day for _____.", category: "Office Life" },
{ scenario: "Scientists found the cure for loneliness, and it involves daily doses of _____.", category: "Junk Science" },
{ scenario: "The local pub's trivia night got controversial when they asked about _____.", category: "Bar Jokes" },
{ scenario: "I've been in a fight with my best friend for three weeks over _____.", category: "Friendship Feuds" },
{ scenario: "The plot twist in the new thriller is that the murderer was motivated by _____.", category: "Entertainment Fails" },
{ scenario: "The worst possible topping on a pizza: _____.", category: "Foodie Fails" },
{ scenario: "My sleep paralysis demon has recently started _____.", category: "Supernatural Shenanigans" },
{ scenario: "The alien abduction report mentioned the probing was fine — the weird part was _____.", category: "Cosmic Regrets" },
{ scenario: "The rejected Monopoly property nobody wanted: _____.", category: "Game Night Disasters" },
{ scenario: "The strangest item ever confiscated at airport security: _____.", category: "Travel Nightmares" },
{ scenario: "The life coach's seminar promised to teach attendees how to monetize _____.", category: "Bad Advice" },
{ scenario: "The zoo had to put up a new sign that read: 'Please do not _____ the animals.'", category: "Animal Incidents" },
{ scenario: "The world's worst pickup line involves bringing up _____.", category: "Dating Disasters" },
{ scenario: "The thing I miss most about being a child is _____.", category: "Life Stages" },
{ scenario: "My bucket list used to include skydiving, but now it just says _____.", category: "Final Words" },
{ scenario: "The new flavour at the ice cream shop is called _____ and it's surprisingly popular.", category: "Foodie Fails" },
{ scenario: "The only thing my therapist and I disagree about is _____.", category: "Shrunk Talk" },
{ scenario: "In another life, I'm pretty sure I was _____.", category: "Past Life Problems" },
{ scenario: "The world's worst DJ goes by the name _____ and exclusively plays _____.", category: "Performance Fails" },
{ scenario: "The neighbourhood watch reported suspicious activity involving _____.", category: "Neighbor Nightmares" },
{ scenario: "At 2 AM, the only food that makes sense is _____.", category: "Late Night Decisions" },
{ scenario: "The breakup note just said: 'It's not me, it's _____.'", category: "Romance Fails" },
{ scenario: "The wedding photographer's biggest regret from the day was _____.", category: "Wedding Chaos" },
{ scenario: "What's the one thing everyone lies about on their CV? _____.", category: "Career Suicide" },
{ scenario: "The strangest item on the antique dealer's shelf: _____.", category: "Weird Attractions" },
{ scenario: "My doctor said if I don't stop _____, I have six months to live.", category: "Medical Mysteries" },
{ scenario: "The worst thing to say to someone who just broke up with you: _____.", category: "Romance Fails" },
{ scenario: "When the power goes out, my neighbors immediately start _____.", category: "Neighbor Nightmares" },
{ scenario: "The worst party theme ever suggested: _____.", category: "Entertainment Fails" },
{ scenario: "My dog has one enemy in this world, and it's _____.", category: "Animal Incidents" },
{ scenario: "The weirdest thing about being a professional clown: _____.", category: "Dying Arts" },
{ scenario: "My horoscope for this week: 'You will find unexpected love in _____.'", category: "Cosmic Regrets" },
{ scenario: "The strangest thing ever found in a couch cushion: _____.", category: "Home Horrors" },
{ scenario: "The chef whispered that the secret to this dish was adding a pinch of _____.", category: "Foodie Fails" },
{ scenario: "The town council voted to ban _____ from all public spaces.", category: "Legal Trouble" },
{ scenario: "The weirdest thing about the witness protection program: _____.", category: "True Crime Lite" },
{ scenario: "My personal trainer's motivational speech ended with the phrase '_____.'", category: "Fitness Fails" },
{ scenario: "The town's only claim to fame is being the birthplace of _____.", category: "Rural Life" },
{ scenario: "The worst possible name for a bakery: _____.", category: "Business Blunders" },
{ scenario: "I accidentally sent a racy text to my _____ instead of my partner.", category: "Tech Problems" },
{ scenario: "The world's most unnecessary reality show: '_____.'", category: "Entertainment Fails" },
{ scenario: "What do morticians listen to while they work? _____.", category: "Behind the Scenes" },
{ scenario: "My grandmother's cure for everything: _____.", category: "Old World Remedies" },
{ scenario: "The strangest phobia listed in the medical journal: a deep fear of _____.", category: "Medical Mysteries" },
{ scenario: "The world's most disappointing theme park: _____ Land.", category: "Entertainment Fails" },
{ scenario: "The worst thing to put as your emergency contact: _____.", category: "Medical Mysteries" },
{ scenario: "The new dating show pairs contestants based on their shared love of _____.", category: "Dating Disasters" },
{ scenario: "The sommelier apologized and said the wine had unexpectedly curdled into _____.", category: "Foodie Fails" },
{ scenario: "The most awkward thing to say at a job interview: '_____.'", category: "Career Suicide" },
{ scenario: "The worst text to wake up to in the morning: '_____.'", category: "Tech Problems" },
{ scenario: "The spy's cover was blown when they were caught buying _____ at the supermarket.", category: "True Crime Lite" },
{ scenario: "The final boss in this video game is _____.", category: "Game Night Disasters" },
{ scenario: "My ex still drunk dials me to talk about _____.", category: "Romance Fails" },
{ scenario: "The world's worst escape room theme: _____.", category: "Entertainment Fails" },
{ scenario: "The worst thing to discover about yourself in your 30s: _____.", category: "Life Stages" },
{ scenario: "The new cocktail on the menu is called The _____ and nobody knows what's in it.", category: "Bar Jokes" },
{ scenario: "What really happens at a bachelorette party? _____.", category: "Wedding Chaos" },
{ scenario: "My landlord raised the rent again because he added _____ to the apartment.", category: "Rental Woes" },
{ scenario: "The reason the scarecrow won an award: _____.", category: "Rural Life" },
{ scenario: "The Guinness World Record for _____ was set in a Walmart parking lot.", category: "Weird Attractions" },
{ scenario: "The only surviving evidence of the party: _____.", category: "Late Night Decisions" },
{ scenario: "The substitute teacher immediately lost control of the class when she tried _____.", category: "School Daze" },
{ scenario: "The petting zoo had all the usual animals, plus one very confused _____.", category: "Animal Incidents" },
{ scenario: "My last relationship ended because we disagreed about _____.", category: "Romance Fails" },
{ scenario: "The most passive-aggressive thing you can cook for someone who wronged you: _____.", category: "Revenge Dishes" },
{ scenario: "The plumber found something unexpected behind the wall, specifically _____.", category: "Home Horrors" },
{ scenario: "The first rule of the book club is that nobody talks about _____.", category: "Book Club Blues" },
{ scenario: "The new exercise craze sweeping retirement communities: _____.", category: "Life Stages" },
{ scenario: "The lost city of Atlantis was actually sunk by _____.", category: "Historical Myths" },
{ scenario: "What's the one thing you should never Google at work? _____.", category: "Office Life" },
{ scenario: "The reason I got banned from that country for life: _____.", category: "Travel Nightmares" },
{ scenario: "The cruise buffet had everything — even _____.", category: "Travel Nightmares" },
{ scenario: "The campfire story everyone was too scared to finish was about _____.", category: "Outdoor Disasters" },
{ scenario: "The one memory from Vegas I'll never share with anyone involves _____.", category: "Vegas Stories" },
{ scenario: "The new rule at my workplace: employees are no longer permitted to _____.", category: "Office Life" },
{ scenario: "The hotel pillow menu included an option called _____.", category: "Lifestyle Choices" },
{ scenario: "The detective's biggest case turned out to involve _____.", category: "True Crime Lite" },
{ scenario: "I thought I was getting a puppy, but instead, I got _____.", category: "Animal Incidents" },
{ scenario: "The scariest thing about being an astronaut isn't space — it's _____.", category: "Cosmic Regrets" },
{ scenario: "The rejected cereal mascot was a character called _____ who kept doing _____.", category: "Questionable Products" },
{ scenario: "My neighbor's midnight prayer turned out to be for _____.", category: "Neighbor Nightmares" },
{ scenario: "The new romantic comedy is about two people who fall in love over their mutual hatred of _____.", category: "Romance Fails" },
{ scenario: "The thing the wine sommelier refused to pair with anything: _____.", category: "Foodie Fails" },
{ scenario: "The karaoke song that empties a bar faster than anything else: _____.", category: "Performance Fails" },
{ scenario: "The worst thing to discover about a house after buying it: _____.", category: "Home Horrors" },
{ scenario: "The world's least popular Airbnb experience: cooking class featuring _____.", category: "Travel Nightmares" },
{ scenario: "The embarrassing thing the background check revealed: _____.", category: "Career Suicide" },
{ scenario: "The janitor at the Louvre has strong opinions about _____.", category: "Behind the Scenes" },
{ scenario: "My friend group has a strict rule: no talking about _____ after 10 PM.", category: "Friendship Feuds" },
{ scenario: "The haunted mansion tour took a turn when the guide started actually _____.", category: "Supernatural Shenanigans" },
{ scenario: "The worst piece of advice Reddit ever gave me: _____.", category: "Tech Problems" },
{ scenario: "The game show's final round involved contestants eating _____.", category: "Entertainment Fails" },
{ scenario: "The name of my memoir: '_____: A Story of Survival.'", category: "Final Words" },
{ scenario: "My spirit guide appeared to me and said only one thing: '_____.'", category: "Supernatural Shenanigans" },
{ scenario: "The street performer's grand finale involved _____.", category: "Performance Fails" },
{ scenario: "My landlord's new house rule is that tenants must not bring _____ onto the premises.", category: "Rental Woes" },
{ scenario: "The fortune teller took one look at my palm and immediately warned me about _____.", category: "Supernatural Shenanigans" },
{ scenario: "The worst thing to find in a fondue pot: _____.", category: "Foodie Fails" },
{ scenario: "My dog looked me dead in the eyes and I'm pretty sure he was thinking about _____.", category: "Animal Incidents" },
{ scenario: "The worst sound to wake up to in a foreign country: _____.", category: "Travel Nightmares" },
{ scenario: "The new trending TikTok challenge involves _____.", category: "Tech Problems" },
{ scenario: "What was found in the locked filing cabinet in the HR office? _____.", category: "Office Life" },
{ scenario: "My Sims character kept dying because of _____.", category: "Game Night Disasters" },
{ scenario: "The world's worst superhero power: _____.", category: "Fantasy Problems" },
{ scenario: "The sushi chef's secret menu item: _____.", category: "Foodie Fails" },
{ scenario: "My ex's new partner is apparently extremely talented at _____.", category: "Romance Fails" },
{ scenario: "The celebrity chef's kitchen was shut down after inspectors found _____.", category: "Foodie Fails" },
{ scenario: "The last person on earth I expected to be a professional _____ was my mother.", category: "Life Stages" },
{ scenario: "The world's most confusing instruction manual was written for _____.", category: "Questionable Products" },
{ scenario: "The weirdest luxury item in the hotel minibar: _____.", category: "Lifestyle Choices" },
{ scenario: "The thing I swore I'd never do after the divorce, but did anyway: _____.", category: "Life Stages" },
{ scenario: "The worst pick-up line that somehow actually worked: '_____.'", category: "Dating Disasters" },
{ scenario: "I walked in on my roommate doing _____. We've never spoken of it.", category: "Roommate Hell" },
{ scenario: "The time capsule from 1995 was opened to reveal nothing but _____.", category: "Historical Myths" },
{ scenario: "The conspiracy theorist's most convincing argument: _____ is fake.", category: "Conspiracy Theories" },
{ scenario: "The one thing I found in my date's bathroom that made me leave immediately: _____.", category: "Dating Disasters" },
{ scenario: "My online shopping addiction has gotten so bad I now own _____.", category: "Tech Problems" },
{ scenario: "The art critic described the painting as 'a bold exploration of _____.'", category: "Art World Nonsense" },
{ scenario: "The strangest symptom of this rare disease: an uncontrollable urge to _____.", category: "Medical Mysteries" },
{ scenario: "The least romantic honeymoon destination: _____.", category: "Wedding Chaos" },
{ scenario: "The new food truck only serves _____ and there's always a line.", category: "Foodie Fails" },
{ scenario: "My landlord's previous tenant left behind _____. He's still not over it.", category: "Rental Woes" },
{ scenario: "The kids' birthday party magician made _____ disappear. It's still gone.", category: "Performance Fails" },
{ scenario: "My cat judges me every time I _____.", category: "Animal Incidents" },
{ scenario: "The world's worst date idea: a romantic evening of _____.", category: "Dating Disasters" },
{ scenario: "The old man at the end of the bar had seen things — specifically _____.", category: "Bar Jokes" },
{ scenario: "The most embarrassing thing I've Googled in the last week: _____.", category: "Tech Problems" },
{ scenario: "Turns out my yoga instructor's day job is _____.", category: "Behind the Scenes" },
{ scenario: "The groomsman speech started well but ended with a detailed story about _____.", category: "Wedding Chaos" },
{ scenario: "The medieval peasants didn't have electricity, but they did have _____.", category: "Historical Myths" },
{ scenario: "The villain's grand plan was ultimately foiled by _____.", category: "Entertainment Fails" },
{ scenario: "The wellness influencer swears by a morning routine that includes _____.", category: "Wellness Nonsense" },
{ scenario: "The one thing Airbnb should warn guests about: _____.", category: "Travel Nightmares" },
{ scenario: "My life coach told me that my biggest obstacle to success is _____.", category: "Bad Advice" },
{ scenario: "The strangest rule in my building's lease: 'Tenants shall not _____ after sundown.'", category: "Rental Woes" },
{ scenario: "The reason the pigeon stared at me for so long: _____.", category: "Animal Incidents" },
{ scenario: "My grandmother still insists that the cure for a bad cold is _____.", category: "Old World Remedies" },
{ scenario: "The world's worst museum tour starts with a lengthy explanation of _____.", category: "Entertainment Fails" },
{ scenario: "The ghost hunter's equipment detected unexpectedly high levels of _____ in the attic.", category: "Supernatural Shenanigans" },
{ scenario: "The new cocktail at the speakeasy is called 'The _____' and it tastes like regret.", category: "Bar Jokes" },
{ scenario: "The DMV asked me to redo my ID photo because of _____.", category: "Legal Trouble" },
{ scenario: "My neighbor has been playing _____ on repeat for three weeks.", category: "Neighbor Nightmares" },
{ scenario: "The saddest thing about working in a circus: _____.", category: "Dying Arts" },
{ scenario: "The country's new national holiday celebrates the anniversary of _____.", category: "Legal Trouble" },
{ scenario: "What's the one thing passengers are thinking but never say to their pilot? _____.", category: "Travel Nightmares" },
{ scenario: "The worst flavour of chewing gum ever made: _____.", category: "Questionable Products" },
{ scenario: "My horoscope said this would be my month for romance, so I tried _____.", category: "Romance Fails" },
{ scenario: "The detective noticed the suspect had suspicious traces of _____ on their fingers.", category: "True Crime Lite" },
{ scenario: "The new fragrance line from a discount brand is called _____ and smells like _____.", category: "Questionable Products" },
{ scenario: "The town's most beloved local legend is the story of _____.", category: "Rural Life" },
{ scenario: "The robot uprising started, not with weapons, but with _____.", category: "Fantasy Problems" },
{ scenario: "The weirdest trend in interior design right now: decorating with _____.", category: "Lifestyle Choices" },
{ scenario: "The rejected episode of a cooking show was about making _____ for a dinner party.", category: "Foodie Fails" },
{ scenario: "The world's dullest country hit single is about _____.", category: "Performance Fails" },
{ scenario: "My date kept nervously mentioning _____. I should have left sooner.", category: "Dating Disasters" },
{ scenario: "The world record attempt failed spectacularly when someone introduced _____ into the mix.", category: "Sports Disasters" },
{ scenario: "My dog's Instagram account has 40,000 followers, all for photos of _____.", category: "Animal Incidents" },
{ scenario: "The last thing I ordered drunk online was _____ and I regret nothing.", category: "Late Night Decisions" },
{ scenario: "The weirdest note left on a car windshield: '_____.'", category: "Neighbor Nightmares" },
{ scenario: "The awkward silence at the dinner party was broken when someone brought up _____.", category: "Awkward Conversations" },
{ scenario: "The world's most unethical personal trainer would recommend _____.", category: "Fitness Fails" },
{ scenario: "When no one's watching, the zookeeper likes to _____.", category: "Behind the Scenes" },
{ scenario: "The world's most specific online forum is dedicated to people who love _____.", category: "Weird Attractions" },
{ scenario: "The time I accidentally said _____ to my boss will haunt me forever.", category: "Career Suicide" },
{ scenario: "The one true test of a long-term relationship: surviving _____.", category: "Life Stages" },
{ scenario: "What actually goes on inside Ikea after closing time? _____.", category: "Behind the Scenes" },
{ scenario: "The scariest chapter in the history book was titled '_____.'", category: "Historical Myths" },
{ scenario: "My life fell apart the day I discovered _____.", category: "Life Stages" },
{ scenario: "The fashion designer's new collection is inspired by _____.", category: "Art World Nonsense" },
{ scenario: "The worst possible band name for a children's birthday party: _____.", category: "Performance Fails" },
{ scenario: "I asked the bartender for his recommendation, and he handed me _____.", category: "Bar Jokes" },
{ scenario: "The one thing I'll never admit to eating at midnight: _____.", category: "Late Night Decisions" },
{ scenario: "The museum's controversial new exhibit: '_____: A Journey Through Time.'", category: "Art World Nonsense" },
{ scenario: "My coworker Karen brings _____ for lunch every day. We are at war.", category: "Office Life" },
{ scenario: "The aliens made first contact, but got immediately distracted by _____.", category: "Cosmic Regrets" },
{ scenario: "The strangest item on the brunch menu: _____ Benedict.", category: "Foodie Fails" },
{ scenario: "My travel insurance didn't cover _____, which was a problem.", category: "Travel Nightmares" },
{ scenario: "The village elder gave me one piece of wisdom: 'Never trust a man who _____.'", category: "Rural Life" },
{ scenario: "The world's most controversial board game involves _____.", category: "Game Night Disasters" },
{ scenario: "My dog once saved my life, but then immediately ruined it by _____.", category: "Animal Incidents" },
{ scenario: "The thing about being a pirate that history books leave out: _____.", category: "Historical Myths" },
{ scenario: "The strangest possible name for a yoga pose: _____.", category: "Fitness Fails" },
{ scenario: "The least motivating gym poster ever printed: '_____.'", category: "Fitness Fails" },
{ scenario: "The one thing I learned in school that has genuinely never come up since: _____.", category: "School Daze" },
{ scenario: "The rejected Hallmark movie was about finding love through _____.", category: "Romance Fails" },
{ scenario: "My interior decorator insisted the living room needed a statement piece, specifically _____.", category: "Home Horrors" },
{ scenario: "My ghost is definitely going to come back and haunt people by _____.", category: "Final Words" },
{ scenario: "The world's least appetizing pizza topping combination: _____ and _____.", category: "Foodie Fails" },
{ scenario: "The noise complaint filed against me involved _____. It was misunderstood.", category: "Legal Trouble" },
{ scenario: "What has the hotel housekeeper definitely seen but will never mention? _____.", category: "Behind the Scenes" },
{ scenario: "My self-help journal has a dedicated section for tracking my progress with _____.", category: "Wellness Nonsense" },
{ scenario: "The one conversation topic that will instantly end a first date: _____.", category: "Dating Disasters" },
{ scenario: "The strangest thing about the tiny house movement is _____.", category: "Lifestyle Choices" },
{ scenario: "My grandpa used to say: 'A real man never _____, unless provoked.'", category: "Old World Remedies" },
{ scenario: "The motivational speaker's speech derailed when they started talking about _____.", category: "Bad Advice" },
{ scenario: "The thing they never teach you in medical school: _____.", category: "Medical Mysteries" },
{ scenario: "The true crime documentary had a twist: the real criminal was actually _____.", category: "True Crime Lite" },
{ scenario: "My dog's vet had concerns about the fact that my dog keeps dreaming about _____.", category: "Animal Incidents" },
{ scenario: "The world's loudest profession is not what you think — it's _____.", category: "Behind the Scenes" },
{ scenario: "The strangest thing sold at a garage sale last weekend: _____.", category: "Weird Attractions" },
{ scenario: "The old castle had a dungeon, a moat, and a mysterious room full of _____.", category: "Historical Myths" },
{ scenario: "In 100 years, historians will be most confused by our obsession with _____.", category: "Future Predictions" },
{ scenario: "The most terrifying job in the animal kingdom is being _____'s dentist.", category: "Animal Incidents" },
{ scenario: "At the speed dating event, my first question was always: 'How do you feel about _____?'", category: "Dating Disasters" },
{ scenario: "The worst part of being a vampire has nothing to do with blood — it's _____.", category: "Fantasy Problems" },
{ scenario: "My Roomba gained sentience and immediately started collecting _____.", category: "Tech Problems" },
{ scenario: "The world's most unqualified person to write a cookbook: _____.", category: "Foodie Fails" },
{ scenario: "The least romantic thing you can do on Valentine's Day: _____.", category: "Romance Fails" },
{ scenario: "The underground poker game was shut down because someone bet _____.", category: "Vegas Stories" },
{ scenario: "The only thing that could make the traffic jam worse: _____.", category: "Commuter Hell" },
{ scenario: "What do plumbers talk about at their annual conference? _____.", category: "Behind the Scenes" },
{ scenario: "The barista misspelled my name as _____ and I'm still not over it.", category: "Awkward Conversations" },
{ scenario: "The rejected invention that never made it past the patent office: _____.", category: "Questionable Products" },
{ scenario: "My greatest fear is dying and being remembered only for _____.", category: "Final Words" },
{ scenario: "The world's worst life hack: '_____.'", category: "Bad Advice" },
{ scenario: "The funniest reason to get fired from a theme park job: _____.", category: "Career Suicide" },
{ scenario: "The weirdest reason given to a judge in a divorce case: '_____.'", category: "Legal Trouble" },
{ scenario: "The thing that should be on the health warning label for alcohol: _____.", category: "Bar Jokes" },
{ scenario: "The thing I found in my rental car that nobody has explained: _____.", category: "Travel Nightmares" },
{ scenario: "The weirdest thing overheard in a sauna: '_____.'", category: "Wellness Nonsense" },
{ scenario: "My Tarot card reader told me that the Tower card in my spread represented _____.", category: "Supernatural Shenanigans" },
{ scenario: "The world's most elaborate excuse for being late to work: '_____.'", category: "Office Life" },
{ scenario: "The ancient Greek philosophers never addressed _____. Big oversight.", category: "Historical Myths" },
{ scenario: "I started meditating but every time I clear my mind, I just think about _____.", category: "Wellness Nonsense" },
{ scenario: "The funniest reason ever listed on a restraining order: '_____.'", category: "Legal Trouble" },
{ scenario: "The only Michelin star restaurant in the country is exclusively serving _____.", category: "Foodie Fails" },
{ scenario: "The most dramatic way to quit your job: _____.", category: "Career Suicide" },
{ scenario: "The new energy drink that claims to be powered entirely by _____.", category: "Questionable Products" },
{ scenario: "My grandmother's favorite party trick is _____. She's 83.", category: "Life Stages" },
{ scenario: "What's the real reason seagulls are so aggressive? _____.", category: "Animal Incidents" },
{ scenario: "The weirdest symptom I Googled at 3 AM that turned out to be completely normal: _____.", category: "Medical Mysteries" },
{ scenario: "The item left behind at the lost and found that nobody claimed: _____.", category: "Weird Attractions" },
{ scenario: "The strangest warning label on a luxury item: 'Do not use near _____.'", category: "Questionable Products" },
{ scenario: "The vampire said his only real weakness wasn't garlic or sunlight — it was _____.", category: "Fantasy Problems" },
{ scenario: "The world record for loudest _____ was set accidentally during a church service.", category: "Weird Attractions" },
{ scenario: "The art installation at the gallery this month is a 6-foot sculpture made entirely of _____.", category: "Art World Nonsense" },
{ scenario: "The most unsettling thing a child has ever said to me: '_____.'", category: "Awkward Conversations" },
{ scenario: "The new couples' therapy technique involves both partners sitting silently while _____.", category: "Wellness Nonsense" },
{ scenario: "The worst thing that can happen during a job interview via Zoom: _____.", category: "Career Suicide" },
{ scenario: "The noise from the haunted house turned out not to be a ghost — just _____.", category: "Home Horrors" },
{ scenario: "The world's most dramatic cause of a pub quiz fight: _____.", category: "Bar Jokes" },
{ scenario: "The most unsettling thing my cat does while I sleep: _____.", category: "Animal Incidents" },
{ scenario: "The last text in the group chat before everyone went silent was '_____.'", category: "Friendship Feuds" },
{ scenario: "My ex sent me a care package after the breakup. Inside was _____.", category: "Romance Fails" },
{ scenario: "The world's worst thing to stumble upon in your attic: _____.", category: "Home Horrors" },
{ scenario: "The reason I am never allowed back in that country: _____.", category: "Travel Nightmares" },
{ scenario: "The world record holder for _____ has never once been invited to a dinner party.", category: "Weird Attractions" },
{ scenario: "My coworker and I had a heated debate about _____ that lasted four hours.", category: "Office Life" },
{ scenario: "The most unexpected thing found inside a birthday cake: _____.", category: "Party Fails" },
{ scenario: "The town's annual festival is dedicated to celebrating _____.", category: "Rural Life" },
{ scenario: "What does a mermaid keep in her purse? _____.", category: "Fantasy Problems" },
{ scenario: "My online dating profile's biggest turn-off: 'I hate people who _____.'", category: "Dating Disasters" },
{ scenario: "The worst time to accidentally start laughing: _____.", category: "Social Disasters" },
{ scenario: "The rejected slogan for a new energy drink: '_____.'", category: "Questionable Products" },
{ scenario: "The sommelier paused, looked at the bottle, and said: 'This pairs best with _____.'", category: "Foodie Fails" },
{ scenario: "The most unconventional thing a personal trainer has ever made a client do: _____.", category: "Fitness Fails" },
{ scenario: "The world's worst advice given in a TEDx talk: '_____.'", category: "Bad Advice" },
{ scenario: "The alien who visited Earth went home and described humans as 'a species obsessed with _____.'", category: "Cosmic Regrets" },
{ scenario: "The most passive-aggressive gift you can give to a coworker: _____.", category: "Office Life" },
{ scenario: "What's the worst thing to find written in a guestbook? '_____.'", category: "Travel Nightmares" },
{ scenario: "The local haunted house's scariest room was titled '_____.'", category: "Supernatural Shenanigans" },
{ scenario: "The world's most unsettling children's book is titled '_____.'", category: "Entertainment Fails" },
{ scenario: "The one thing that could make a long-haul flight worse: _____.", category: "Travel Nightmares" },
{ scenario: "The strangest place I've ever found socks: _____.", category: "Home Horrors" },
{ scenario: "My new tattoo was supposed to say something meaningful, but instead it says _____.", category: "Bad Decisions" },
{ scenario: "The thing you should never, under any circumstances, mention at a dinner party: _____.", category: "Awkward Conversations" },
{ scenario: "My spirit animal took one look at me and immediately requested a transfer to _____.", category: "Self Discovery" },
{ scenario: "The world's most unnecessary bumper sticker: '_____.'", category: "Questionable Products" },
{ scenario: "The worst ever best man speech ended with the revelation that _____.", category: "Wedding Chaos" },
{ scenario: "My search history on a Tuesday afternoon is just: _____ and _____.", category: "Tech Problems" },
{ scenario: "The haunted house's least scary room was the one dedicated entirely to _____.", category: "Supernatural Shenanigans" },
{ scenario: "The newest extreme diet requires you to eat nothing but _____ for an entire month.", category: "Wellness Nonsense" },
{ scenario: "The cat judged me. The dog forgave me. The goldfish was too busy thinking about _____.", category: "Animal Incidents" },
{ scenario: "The weirdest part of the alien abduction was when they asked me to explain _____.", category: "Cosmic Regrets" },
{ scenario: "The worst possible Scrabble word to open with: _____.", category: "Game Night Disasters" },
{ scenario: "My spirit guide gave me one warning before vanishing: 'Don't ever _____.'", category: "Supernatural Shenanigans" },
{ scenario: "The most dramatic thing to happen at a book club meeting: _____.", category: "Book Club Blues" },
{ scenario: "The new gym class that nobody asked for but everyone is joining: _____.", category: "Fitness Fails" },
{ scenario: "What's the worst thing to find in the lost and found at a nudist resort? _____.", category: "Lifestyle Choices" },
{ scenario: "The underground supper club's secret menu item was described only as '_____.'", category: "Foodie Fails" },
{ scenario: "My biography would be a short but compelling book titled '_____.'", category: "Final Words" },
{ scenario: "The worst thing about being a ghost: _____.", category: "Fantasy Problems" },
{ scenario: "My taxi driver's one piece of life advice: '_____.'", category: "Awkward Rides" },
{ scenario: "The most dramatic intervention ever held was about someone's addiction to _____.", category: "Medical Mysteries" },
{ scenario: "The new banned word in the office: '_____.' Nobody knows why.", category: "Office Life" },
{ scenario: "The world's most unconvincing disguise involved _____.", category: "True Crime Lite" },
{ scenario: "I asked the psychic what my greatest gift is. She said _____. I'm still confused.", category: "Self Discovery" },
{ scenario: "The strangest Craigslist ad ever posted was for _____. It sold immediately.", category: "Weird Attractions" },
{ scenario: "My landlord knocked on my door to complain about the smell of _____.", category: "Rental Woes" },
{ scenario: "The last thing anyone expected at the school reunion was _____.", category: "School Daze" },
{ scenario: "The most embarrassing thing to get caught doing at the library: _____.", category: "School Daze" },
{ scenario: "The saddest part of a food festival is always _____.", category: "Foodie Fails" },
{ scenario: "The one thing that separates a good camping trip from a great one: _____.", category: "Outdoor Disasters" },
{ scenario: "The world's worst financial advice: '_____.'", category: "Bad Advice" },
{ scenario: "The ghost tour's terrifying twist: the ghost wasn't a ghost — it was _____.", category: "Supernatural Shenanigans" },
{ scenario: "What do taxi drivers say about their passengers when they think no one is listening? _____.", category: "Awkward Rides" },
{ scenario: "My financial advisor told me to invest everything in _____. I'm in debt.", category: "Bad Decisions" },
{ scenario: "The strangest chapter heading in an otherwise normal autobiography: '_____.'", category: "Legacy Fails" },
{ scenario: "The world's most alarming ingredient on a nutrition label: _____.", category: "Foodie Fails" },
{ scenario: "The world's least successful band was called _____ and their one hit was '_____.'", category: "Performance Fails" },
{ scenario: "The psychologist said my recurring dream about _____ is totally normal. It is not.", category: "Shrunk Talk" },
{ scenario: "The real reason flamingos stand on one leg: _____.", category: "Animal Incidents" },
{ scenario: "The terrible icebreaker at the work conference: 'Tell us your name and your biggest _____.'", category: "Office Life" },
{ scenario: "What's the last thing you want to hear just before a parachute jump? '_____.'", category: "Extreme Nonsense" },
{ scenario: "The world's worst Tinder bio includes the phrase: 'I'm not like other guys, I _____.'", category: "Dating Disasters" },
{ scenario: "The world's worst hotel breakfast features a buffet of _____.", category: "Travel Nightmares" },
{ scenario: "The thing my autopilot mode has me doing every morning without fail: _____.", category: "Self Discovery" },
{ scenario: "The most upsetting prize in a raffle: _____.", category: "Party Fails" },
{ scenario: "The plumber looked under my sink and asked if I was doing okay. Apparently, _____.", category: "Home Horrors" },
{ scenario: "My internet search history is equal parts cooking recipes and _____.", category: "Self Discovery" },
{ scenario: "The world record for _____ was set in this very town and nobody talks about it.", category: "Rural Life" },
{ scenario: "The worst thing about a silent retreat: _____.", category: "Wellness Nonsense" },
{ scenario: "The funniest reason to get thrown out of a library: _____.", category: "School Daze" },
{ scenario: "The most unexpected celebrity endorsement: _____ promoting _____.", category: "Questionable Products" },
{ scenario: "The ancient map had one final destination marked with a skull: _____.", category: "Historical Myths" },
{ scenario: "The emergency services log simply listed the incident as involving _____.", category: "Legal Trouble" },
{ scenario: "My horoscope said Mercury in retrograde would affect my _____. It was not wrong.", category: "Cosmic Regrets" },
{ scenario: "The world's least inspiring national anthem is about _____.", category: "Legacy Fails" },
{ scenario: "The most inexplicably popular street food: _____.", category: "Foodie Fails" },
{ scenario: "The wedding toast started with 'I always knew these two were meant for each other because _____.'", category: "Wedding Chaos" },
{ scenario: "My meditation app sent me a notification that just said '_____.' I uninstalled it.", category: "Wellness Nonsense" },
{ scenario: "The world's worst thing to happen during a magic trick: _____.", category: "Performance Fails" },
{ scenario: "The strangest question on my driving test: '_____?'", category: "Legal Trouble" },
{ scenario: "The most terrifying message ever sent via carrier pigeon: '_____.'", category: "Historical Myths" },
{ scenario: "My ex left behind a box of stuff that includes _____ and I don't know how to return it.", category: "Romance Fails" },
{ scenario: "The worst possible name for a hair salon: _____.", category: "Business Blunders" },
{ scenario: "The thing I miss most about living alone: never having to explain _____.", category: "Roommate Hell" },
{ scenario: "The new reality show pairs people with their worst habit, which in Episode 1 was _____.", category: "Entertainment Fails" },
{ scenario: "The worst fortune cookie message ever: '_____.'", category: "Cosmic Regrets" },
{ scenario: "The strangest reason given for calling in sick to work: '_____.'", category: "Office Life" },
{ scenario: "I finally answered the question my therapist has been asking for years: _____.", category: "Shrunk Talk" },
{ scenario: "The world's least useful survival skill: _____.", category: "Survival Strategy" },
{ scenario: "The thing I regret ordering at 1 AM more than anything else: _____.", category: "Late Night Decisions" },
{ scenario: "In a post-apocalyptic world, the currency will be _____.", category: "Future Predictions" },
{ scenario: "The only reason I go to the gym is to _____.", category: "Fitness Fails" },
{ scenario: "The most unhinged behavior I've witnessed at an all-inclusive resort: _____.", category: "Travel Nightmares" },
{ scenario: "My cat has been staring at the same corner of the room for three days. It's definitely _____.", category: "Supernatural Shenanigans" },
{ scenario: "The world's most terrifying children's party entertainer specializes in _____.", category: "Party Fails" },
{ scenario: "The thing you should never put on a resume under 'special skills': _____.", category: "Career Suicide" },
{ scenario: "When I'm stressed, I comfort myself with _____. My therapist is concerned.", category: "Shrunk Talk" },
{ scenario: "The last text I sent before losing my phone was about _____.", category: "Tech Problems" },
{ scenario: "The most dramatic exit from a dinner party ever executed: _____.", category: "Social Disasters" },
{ scenario: "The world's saddest souvenir is a snow globe containing _____.", category: "Weird Attractions" },
{ scenario: "The thing that made me realize I needed a new life direction: _____.", category: "Life Stages" },
{ scenario: "The one warning I give all new roommates: 'Whatever you do, don't _____.'", category: "Roommate Hell" },
{ scenario: "The strangest item on an upscale restaurant's bill: '_____' — $85.", category: "Foodie Fails" },
{ scenario: "My dog is an absolute disaster on walks because of _____.", category: "Animal Incidents" },
{ scenario: "The world's most terrifying thing to hear your pilot say over the intercom: '_____.'", category: "Travel Nightmares" },
{ scenario: "The detective noticed the butler was suspicious because he kept _____.", category: "True Crime Lite" },
{ scenario: "The world's most depressing theme park ride: '_____: The Experience.'", category: "Entertainment Fails" },
{ scenario: "The world's worst professional wrestling name and signature move: _____ with the _____.", category: "Sports Disasters" },
{ scenario: "My phone's most used emoji is _____ and I refuse to explain.", category: "Self Discovery" },
{ scenario: "The world's most confusing instruction on a shampoo bottle: '_____.'", category: "Questionable Products" },
{ scenario: "My midlife crisis manifested as a sudden obsession with _____.", category: "Life Stages" },
{ scenario: "The saddest meal I've ever eaten was _____ alone at 11 PM.", category: "Late Night Decisions" },
{ scenario: "The new trend in luxury tourism: paying $5,000 to experience _____.", category: "Lifestyle Choices" },
{ scenario: "The most unlikely person to be running an underground _____ ring: my accountant.", category: "True Crime Lite" },
{ scenario: "The thing I'll be most embarrassed about in 20 years: my current obsession with _____.", category: "Future Predictions" },
{ scenario: "The strangest museum in the world is dedicated entirely to _____. It has great reviews.", category: "Weird Attractions" },
 


];
