/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Challenge } from "./types.js";

export const CHALLENGES: Challenge[] = [
  // --- HEIST & CRIME ABSURDITIES ---
  { scenario: "You must rob a high-security bank using only a raw potato and a plastic soup spoon.", category: "Heist Masterclass" },
  { scenario: "You must sneak past lasers and guard dogs using only a jar of pickled onions and a kazoo.", category: "Stealth Tactics" },
  { scenario: "The security guards caught you stealing. You must explain why your pockets are filled with exactly 47 frozen fish sticks.", category: "Caught Red-Handed" },
  { scenario: "You are planning a getaway after stealing the Eiffel Tower. What is your ridiculously impractical exit vehicle?", category: "Grand Theft Tower" },
  { scenario: "Your high-tech laser-cutter broke during a safehouse break-in. What household item are you using to melt steel?", category: "DIY Espionage" },
  { scenario: "You have to disable a motion-detector grid by executing an incredibly specific and humiliating interpretive dance.", category: "Laser Ballet" },
  { scenario: "You must convince a bank teller that your banana is a highly unstable prototype plasma weapon.", category: "Potassium Threat" },
  { scenario: "You have to smuggle 100 live frogs across the border. What is your genius concealment system?", category: "Amphibian Contraband" },
  { scenario: "You accidentally stole a giant velvet painting of Jeff Goldblum instead of the Mona Lisa. Pitch it to your crime boss.", category: "Art Heist Blunder" },
  { scenario: "You need to hotwire a hyper-intelligent self-driving getaway car that refuses to move unless you compliment its tires.", category: "Car Whisperer" },
  { scenario: "Your criminal alias is highly threatening on paper, but sounds like a cute toddler's toy out loud. Deal with it.", category: "Underworld PR" },
  { scenario: "To join an elite league of mime thieves, you must write a threatening ransom note using only invisible gestures.", category: "Silent Syndicate" },
  { scenario: "Your getaway driver is a very enthusiastic golden retriever. How do you direct him to navigate the busy city streets?", category: "Co-Pilot Canine" },
  { scenario: "You must break into a secret military facility dressed as a very sassy giant hot dog.", category: "Infiltration Fashion" },
  { scenario: "You accidentally left your custom robber business card at the crime scene. What does the card say to throw off the FBI?", category: "Dumb Clues" },
  { scenario: "You are interrogating a suspect, but the only good cop/bad cop routine you can pull off is 'Confused Cop' and 'Very Hungry Cop'.", category: "Interrogation Playbook" },
  { scenario: "You've been caught counterfeiting money with crayon drawings of George Washington. Defend your artistic license.", category: "Creative Finance" },
  { scenario: "You need to escape a high-security prison using only office supplies and your pure, raw charisma.", category: "The Great Breakout" },
  { scenario: "A security guard corners you. Quick! Pretend to be a highly complex, expensive piece of smart-museum architecture.", category: "Modern Art Defense" },
  { scenario: "You are breaking into a secure server room, but you have to type the hack code using only your nose.", category: "Nose Hacker" },

  // --- DIPLOMACY & EXTRATERRESTRIAL ---
  { scenario: "Aliens demand proof that humanity deserves to survive, but you only have a recorder and a half-eaten tuna sandwich.", category: "Intergalactic IQ" },
  { scenario: "A Martian diplomat wants to buy Earth for three glow-in-the-dark stickers and a bouncy ball. Negotiate a better deal.", category: "Galactic Real Estate" },
  { scenario: "You must explain the concept of comedy to an advanced alien race that communicates entirely through math equations and sighs.", category: "Cosmic Stand-Up" },
  { scenario: "An alien warlord is about to vaporize London unless you can explain why humans enjoy watching cat videos.", category: "Peline Philosophy" },
  { scenario: "You accidentally sneezed on the Ambassador of Alpha Centauri, which in their culture is an official declaration of marriage.", category: "Cosmic Unions" },
  { scenario: "You need to disguise yourself as a native of Jupiter. The only materials you have are tinfoil and two vacuum cleaner hoses.", category: "Deep-Space Fashion" },
  { scenario: "An alien pet escapes on your watch. It looks like a melting brick of butter and vibrates at the frequency of jazz.", category: "Beast Master" },
  { scenario: "You represent Earth at the Council of Stars. What is the official earthly anthem you play from your outdated iPod Nano?", category: "Eurovision: Space Edition" },
  { scenario: "An alien probe arrives and demands to speak with our 'supreme overlord', who happens to be a very cranky chihuahua.", category: "Interstellar Audits" },
  { scenario: "You accidentally terraformed Mars into a giant ball of jelly. Explain your methodology to the science academy.", category: "Space Kitchen" },
  { scenario: "A telepathic space whale asks you for driving directions to the nearest black hole. What landmarks do you use?", category: "Aquatic Astronavigation" },
  { scenario: "An alien abduction goes wrong when the aliens find your collection of weirdly detailed fan fiction about laundry detergent brands.", category: "Confused Abductors" },
  { scenario: "You need to convince the Galactic Federation that gas station sushi is a sacred, highly dangerous Earth artifact.", category: "High-Risk Culinary" },
  { scenario: "A cosmic bounty hunter tracks you down, but they will spare you if you teach them how to do the Macarena.", category: "Dancing in the Stars" },
  { scenario: "You accidentally got elected as the Emperor of the Milky Way because of a spelling mistake on your LinkedIn profile.", category: "Career Ascendancy" },
  { scenario: "You have to explain to a space council why Earth has so many warning labels on totally edible-looking tide pods.", category: "Humanity's Finest" },
  { scenario: "The planet's atmosphere is depleting. Your solution is to patch the hole using a ridiculous combination of household sprays.", category: "Atmospheric Repairs" },
  { scenario: "An alien race only understands human culture through old television commercials. Pitch them our military defense strategy.", category: "Ad Campaign War" },
  { scenario: "You are hosting the first intergalactic potluck, but the gaseous entity from Saturn is complaining that your salad is 'too solid'.", category: "Host of the Century" },
  { scenario: "A hyper-advanced droid demands to know why humans leak salty fluids from their eyes when they look at pictures of baby otters.", category: "Emotional Algorithm" },

  // --- HISTORICAL & TIME TRAVEL ---
  { scenario: "You have to explain the concept of wireless internet to George Washington, who is currently holding loaded muskets.", category: "Founding Father Chat" },
  { scenario: "A Victorian child is crying because of the cold. Give them a modern meme explanation that will cure their existential dread.", category: "Time Travel Ethics" },
  { scenario: "You are stuck in medieval Europe. What modern concept do you pitch to the local king to avoid being burned as a wizard?", category: "Medieval Shark Tank" },
  { scenario: "You accidentally dropped a smartphone into Ancient Rome. How do you explain the glowing glass brick to Caesar's senate?", category: "Roman Tech Support" },
  { scenario: "You are prehistoric caveman presenting a brand-new invention: 'The Wheel 2.0'. What does it do and why does it require a subscription?", category: "Prehistoric Startup" },
  { scenario: "You travel to the year 3026 and discover that the global currency is now old, scratched-up DVDs of the movie 'Shrek'.", category: "Future Economics" },
  { scenario: "You are trying to convince Cleopatra that your modern cargo pants are the height of royal elegance and tactical storage.", category: "Ancient Runway" },
  { scenario: "A medieval knight challenges you to joust. Your horse is actually a rascal scooter and your lance is a pool noodle.", category: "Chivalry is Alive" },
  { scenario: "You accidentally became the chef for a notoriously picky ancient Spartan army. What is your high-protein, zero-taste menu?", category: "Spartan Kitchen" },
  { scenario: "You are stuck in the 1920s and must describe a computer virus using only slang from the roaring twenties.", category: "Retro Cybersecurity" },
  { scenario: "You accidentally butterfly-effected history so that dinosaurs never went extinct—they just became extremely polite British gentlemen.", category: "Gentle Raptors" },
  { scenario: "You are defending yourself in a 1600s pirate court. Your crime: using a modern laser pointer to confuse the captain's parrot.", category: "Pirate Justice" },
  { scenario: "You need to convince a Viking warlord that eating a whole tub of ice cream is a sacred warrior's ritual to build frost resistance.", category: "Viking Diet" },
  { scenario: "You accidentally brought a microwave back to the Stone Age. Describe the cave painting that explains how to cook pizza rolls.", category: "Stone Age Manual" },
  { scenario: "You are trying to sell a Victorian ghost a timeshare in a modern, highly populated, fully functional Amazon fulfillment center.", category: "Supernatural Broker" },
  { scenario: "You are trying to explain the stock market to a group of confused, pitchfork-wielding peasants in 1342.", category: "Peasant Finance" },
  { scenario: "You travel back in time to stop a major historical event, but you get distracted trying to explain how a toaster works.", category: "Toaster Distraction" },
  { scenario: "You are the court jester for a very depressed King Henry VIII. What is your life-saving, zero-head-loss joke?", category: "Jester or Bust" },
  { scenario: "You accidentally brought an entire modern high school marching band to the Battle of Waterloo. How do you deploy them?", category: "Tactical Symphony" },
  { scenario: "You are trying to convince a Neanderthal that your modern electric toothbrush is a sacred weapon of the storm gods.", category: "Primitive Magic" },

  // --- SOCIAL MISSTAPPES & ETIQUETTE ---
  { scenario: "You match with your own boss on a chaotic dating app. Your only option is to play it cool or double down on crazy.", category: "Career Choices" },
  { scenario: "Your credit card gets declined at an ultra-posh restaurant. Convince the head waiter that your pocket watch is a time machine.", category: "Dining and Dashing" },
  { scenario: "You forgot your spouse's name at your own wedding reception. How do you address them in your formal thank-you speech?", category: "Matrimonial Panic" },
  { scenario: "You are caught sleeping in a very important meeting. What is the highly professional scientific excuse you quickly blurt out?", category: "Corporate Hibernation" },
  { scenario: "You accidentally sent an incredibly heated text complaining about your landlord to your landlord. Smooth it over.", category: "Rental Crisis" },
  { scenario: "You are at a high-society tea party and your stomach makes a noise that sounds exactly like a dying seal. Explain yourself.", category: "Gastric Symphonies" },
  { scenario: "You are introducing your new partner to your highly traditional grandparents, but your partner is wearing a full shrek costume.", category: "Family Dinners" },
  { scenario: "You walked out of the restaurant bathroom with a long trail of toilet paper stuck to your shoe. Build a trend around it.", category: "High Fashion" },
  { scenario: "You are stuck in an elevator with a mime who is slowly losing his mind. What is your strategy to keep the peace?", category: "Silent Crisis" },
  { scenario: "You accidentally walked into the wrong apartment, sat down on the couch, and ate half a stranger's lasagna. Pitch your defense.", category: "Lasagna Squatter" },
  { scenario: "You waved back at someone who was actually waving at the person standing directly behind you. How do you recover?", category: "Waving Disasters" },
  { scenario: "You are caught trying to sneak your own giant bag of spaghetti into a highly fancy, no-outside-food movie theater.", category: "Spaghetti Smuggler" },
  { scenario: "You are giving a eulogy but you accidentally read your weekly grocery list instead. Turn it into a beautiful metaphor.", category: "Laudable Legumes" },
  { scenario: "You accidentally coughed and spit out a whole cherry tomato onto a stranger's pristine white jacket. How do you spin this?", category: "Spontaneous Agriculture" },
  { scenario: "You are trapped in a corner conversation with a guy who won't stop explaining the deep lore of competitive marble racing.", category: "Sports Experts" },
  { scenario: "You need to decline a wedding invitation because you have a very important appointment to watch paint dry on your custom barn.", category: "Priorities First" },
  { scenario: "You are caught trying to parallel park, but you have hit the same parked car 4 times in front of a outdoor patio crowd.", category: "Steering Challenges" },
  { scenario: "You accidentally liked a 7-year-old photo of your ex's new partner's cousin's dog at 3 AM. What is your cover-up?", category: "Digital Footprints" },
  { scenario: "You are trying to leave a terrible party without anyone noticing, but your shoes squeak like a family of angry rubber ducks.", category: "Squeaky Exit" },
  { scenario: "You must explain to your neighbors why there is a giant inflatable bouncy castle currently blocking their driveway.", category: "Property Disputes" },

  // --- ANIMAL REVOLTS & BEHAVIOR ---
  { scenario: "A goose has challenged you to an honorable formal duel. Winning gets you sourdough; losing gets you public humiliation.", category: "Honorable Combat" },
  { scenario: "A group of hyper-intelligent squirrels accuses you of stealing their stash of legendary, golden-plated acorns.", category: "Squirrel Court" },
  { scenario: "You have 5 minutes to convince your cat that you are, in fact, the supreme leader of the household.", category: "Feline Sovereignty" },
  { scenario: "An army of highly intelligent pigeons is correcting your grammar in public. How do you defeat their orthographic reign?", category: "Spelling Airforce" },
  { scenario: "A very polite bear bursts into your cabin and demands a cup of matcha latte. How do you break it to him that you only have instant coffee?", category: "Bear Barista" },
  { scenario: "You have been hired to translate a dog's barking. It turns out he's just reviewing different brands of grass. Write a review.", category: "Canine Critic" },
  { scenario: "A group of seagulls has taken your car keys hostage. They want 5 boxes of hot french fries or the keys go in the ocean.", category: "Avian Ransom" },
  { scenario: "You are accidentally elected as the leader of a cult of very enthusiastic, worshipful garden snails. What are your commandments?", category: "Es-cargo Cult" },
  { scenario: "Your pet goldfish has somehow obtained a miniature megaphone and is shouting financial advice at 2:00 AM.", category: "Aquatic WallStreet" },
  { scenario: "A swarm of bees is paint-balling your house with actual honey because they dislike your choice of lawn ornaments.", category: "Bee-Utiful Devastation" },
  { scenario: "You are running for mayor, but your chief political opponent is an incredibly handsome alpaca who promises free hay for all.", category: "Local Politics" },
  { scenario: "You are trying to teach a penguin how to play the electric guitar. What is your teaching philosophy?", category: "Chilly Rockstars" },
  { scenario: "A pack of wolves has invited you to their campfire, but you must bring a side dish that isn't raw meat. What's on the menu?", category: "Lupine Cuisine" },
  { scenario: "Your dog has started a highly successful podcast where they just complain about your choice of dog food. Defend your brand.", category: "Pooch Podcast" },
  { scenario: "A very sassy parrot is telling the entire neighborhood your actual social security number. How do you silence the bird?", category: "Identity Theft Avian" },
  { scenario: "An ostrich has cornered you at a petrol station and demands you fill its tank. The ostrich does not have a car.", category: "Station Stand-offs" },
  { scenario: "You are trying to negotiate a peaceful border treaty with a hyper-territorial badger who lives in your vegetable drawer.", category: "Veggie Wars" },
  { scenario: "A family of raccoons has turned your attic into a highly popular, underground jazz club. What is your cover charge?", category: "Attic Beats" },
  { scenario: "You are trying to train a squad of tactical frogs to deliver small, message-carrying capsules across a swampy golf course.", category: "Ribbit Courier" },
  { scenario: "Your horse has decided it is now a vegan influencer and refuses to carry you unless you are wearing certified organic cotton.", category: "Equine Ethics" },

  // --- HOUSEHOLD & APPLIANCE CRAZINESS ---
  { scenario: "You wake up to find you have swapped bodies with a very emotional, passive-aggressive smart microwave.", category: "Kitchen Science" },
  { scenario: "Your smart fridge has locked itself and demands you write a 500-word essay about the history of celery before it opens.", category: "Cold Storage Lockout" },
  { scenario: "Your vacuum cleaner has developed a fear of dust and refuse to leave its charging station. How do you therapy-talk it out?", category: "Appliance Healing" },
  { scenario: "Your smart lights have gone rogue and will only shine in hot pink when you are trying to sleep. Negotiate a bedtime.", category: "Luminescent Rebellion" },
  { scenario: "Your toilet has joined a union and is demanding a premium, three-ply toilet paper upgrade before it will flush again.", category: "Sanitation Strike" },
  { scenario: "You bought a budget smart-mirror that only displays your face with cartoon filters from 2012. Fix your self-esteem.", category: "Reflective Errors" },
  { scenario: "Your washing machine is hosting a tiny rave inside itself during the spin cycle. What tracks are the damp socks dancing to?", category: "Spin Cycle Beats" },
  { scenario: "Your toaster only burns bread in patterns of extremely complicated stock market graphs. Read the bread for tomorrow's forecast.", category: "Toaster Analytics" },
  { scenario: "Your automated lawnmower has declared your backyard an independent republic and is currently writing a constitution.", category: "Mower Sovereignty" },
  { scenario: "Your smart thermostat will only adjust the temperature if you sing it a tender, slow-tempo love song.", category: "Thermal Romance" },
  { scenario: "You bought a secondhand robotic vacuum that has developed a deep, dark hoarding habit. It hides shiny items under the sofa.", category: "Robotic Hoarder" },
  { scenario: "Your wireless router is asking for a personal day off because it's 'feeling spiritually clogged by all your search queries'.", category: "Network Block" },
  { scenario: "Your ceiling fan only has two settings: 'Deadly Quiet' and 'Hurricane Category 5'. Convince guests it's a feature, not a bug.", category: "Airy Disasters" },
  { scenario: "Your smart kettle refuses to boil water because it believes tea is 'capitalist leaf broth'. Convert it back to brewing.", category: "Strikethrough Boiling" },
  { scenario: "Your automatic dog-feeder has begun rationing food because it believes the dog is 'lacking core discipline'.", category: "Robo-Nanny" },
  { scenario: "Your Bluetooth speaker is extremely opinionated and will loudly criticize your choice of podcasts in the middle of a shower.", category: "Audio Judgment" },
  { scenario: "Your smart blender refuses to blend green smoothies because it says 'grass does not belong in a whirlpool of steel'.", category: "Blender Rebellion" },
  { scenario: "Your electric toothbrush has started vibrating in Morse code to leak government secrets to your bathroom floor tiles.", category: "Dental Intelligence" },
  { scenario: "Your smart lock will only open your front door if you tell it a joke that makes its digital interface giggle.", category: "Comedy Security" },
  { scenario: "Your TV is holding your streaming queue hostage until you go outside and touch a real, physical piece of grass.", category: "Reality Checks" },

  // --- FAULTY SUPERPOWERS ---
  { scenario: "You can turn invisible, but only while screaming at the absolute top of your lungs in public.", category: "Flawed Powers" },
  { scenario: "You can fly, but only at a maximum speed of 2 miles per hour and only while holding a very heavy bucket of water.", category: "Laid-Back Aviation" },
  { scenario: "You can read minds, but you can only hear what people are currently thinking about different types of cheese.", category: "Lactose Intelligence" },
  { scenario: "You have super strength, but only when you are completely and utterly crying your eyes out during a sad movie.", category: "Emotional Muscles" },
  { scenario: "You can teleport anywhere in the world, but your clothes stay behind and you always land in a very public fountain.", category: "Fountain Landing" },
  { scenario: "You have the ability to speak to animals, but they all have extremely thick, hard-to-understand Scottish accents.", category: "Highland Whispers" },
  { scenario: "You can predict the future, but only things that will happen in the next 3 seconds. How do you save the world?", category: "Ultra-Short Oracle" },
  { scenario: "You can summon any object you want, but it always appears directly inside a bowl of hot lukewarm soup on your lap.", category: "Soup Conjurer" },
  { scenario: "You are invulnerable to all damage, but you are also incredibly allergic to paper, meaning you can't touch mail.", category: "Fragile Immortality" },
  { scenario: "You can control fire, but only fire that is currently burning on top of a very expensive birthday candle.", category: "Cupcake Pyromancer" },
  { scenario: "You can speak every human language, but you can only speak in the tone of a very enthusiastic 7-year-old on a sugar rush.", category: "Global Babble" },
  { scenario: "You have the power of x-ray vision, but it only works when you are looking through a slice of Swiss cheese.", category: "Dairy Scanners" },
  { scenario: "You can run at the speed of light, but your steering is so bad that you can only run in a perfectly straight line.", category: "Linear Speedster" },
  { scenario: "You can shoot laser beams from your eyes, but they are only about as hot as a very mildly warm cup of chamomile tea.", category: "Soothing Eye-Beams" },
  { scenario: "You can duplicate yourself, but your clones are all extremely lazy and will immediately lie down and fall asleep.", category: "Sloth Division" },
  { scenario: "You have the ability to walk through walls, but you always get stuck halfway and have to wiggle out while apologizing.", category: "Permeable Failures" },
  { scenario: "You can control magnetic metals, but only metals that are shaped like very specific animal-shaped paperclips.", category: "Stationery Magneto" },
  { scenario: "You have the power of super-hearing, but you can only hear people whispering about whether or not you look tired.", category: "Self-Conscious Audio" },
  { scenario: "You can breathe underwater, but only while wearing a formal three-piece tuxedo and holding a briefcase.", category: "Deep-Sea Business" },
  { scenario: "You can heal any injury with a single touch, but the healed person instantly develops a terrible, uncontrollable urge to yodel.", category: "Alpine Medicine" },

  // --- UNHINGED FOOD & GASTRO ---
  { scenario: "You have accidentally invented a new flavor of ice cream called 'Panic Attack'. Describe the ingredients.", category: "Frozen Terrors" },
  { scenario: "You are open a restaurant, but the only food style you serve is 'Slightly Confused Microwave Cuisine'. Pitch your menu.", category: "High-End Heating" },
  { scenario: "You have to explain to a highly respected Italian chef why you put pineapple, ketchup, and chocolate on your pasta.", category: "Culinary Treason" },
  { scenario: "You are entered into a competitive eating contest where the food is raw onions in a pool of lukewarm mayonnaise.", category: "Deep Gastronomy" },
  { scenario: "You must convince a luxury food inspector that your burnt toast is actually 'deconstructed charcoal sourdough'.", category: "Snobby Diners" },
  { scenario: "You accidentally drank a bottle of salad dressing thinking it was a healthy wellness shot. How do you save face?", category: "Vinaigrette Regrets" },
  { scenario: "You are pitching a new energy drink called 'Maximum Twitch'. What is the secret ingredient that makes people shake?", category: "Liquid Agitation" },
  { scenario: "A futuristic food dispenser will only give you a burger if you describe the burger using incredibly romantic poetry.", category: "Buns and Roses" },
  { scenario: "You accidentally ordered a pizza with 'everything' on it, and now there is a small, conscious ecosystem living on it.", category: "Pizza Planets" },
  { scenario: "You must survive a high-stakes baking show where the secret ingredient is literal, fresh grass from the nearest golf course.", category: "Great British Bake-Off" },
  { scenario: "You are trying to convince your family that your completely raw, unseasoned potato salad is a modern culinary triumph.", category: "Family Picnics" },
  { scenario: "You accidentally replaced the salt in your cookies with highly concentrated, extremely sour lemon powder.", category: "Baking Blunders" },
  { scenario: "You are hired as the personal chef for a vampire who is also extremely allergic to blood. Describe the menu swap.", category: "Vegan Dracula" },
  { scenario: "Your soup is currently making a whistling noise that sounds like a kettle. How do you explain this to the table?", category: "Vaporous Veggies" },
  { scenario: "You must explain to a diner why your restaurant's soup of the day is just a bowl of hot water with a single crouton.", category: "Minimalist Broth" },
  { scenario: "You are trying to market a new cereal called 'Cap'rn Cardboard'. Sell it based on its ultra-high fiber content.", category: "Crunchy Fibers" },
  { scenario: "You are at a buffet and have stacked exactly 85 shrimp on your plate. A nearby customer is judging you. Defend your tower.", category: "Shrimp Monopoly" },
  { scenario: "You accidentally got your hand stuck inside a jar of mayonnaise during a very formal black-tie dinner party.", category: "Mayo Monarch" },
  { scenario: "You are trying to convince your friends that drinking pickle juice is the only way to align their spiritual chakras.", category: "Brine Medicine" },
  { scenario: "You are hosting a cooking channel, but you forgot all the names of your utensils. Refer to them with descriptive nicknames.", category: "Descriptive Chefs" },

  // --- TECH & CORPORATE CAPITALISM ---
  { scenario: "You are pitching a startup that sells high-quality, organic, hand-picked anxiety to wealthy tech executives.", category: "Venture Capitalism" },
  { scenario: "You must write an out-of-office automated email that explains you are away because you are trying to find your lost sanity.", category: "Corporate Communications" },
  { scenario: "Your company is replacing all chairs with giant inflatable exercise balls. Pitch this to a very old-school board.", category: "Ergonomic Horrors" },
  { scenario: "You accidentally hit 'reply all' to a company-wide email with a very detailed plan to fake your own death.", category: "HR Nightmares" },
  { scenario: "Your company has started using 'AI-driven team building' which is just a robot that forces you to hug your coworkers.", category: "Synthetic Synergy" },
  { scenario: "You are in a job interview and they ask for your biggest weakness. You answer: 'I have a very itchy trigger finger with emojis'.", category: "Interview Strategy" },
  { scenario: "You need to write a performance review for your coworker who is literally just a very quiet, well-dressed potted plant.", category: "Foliage Staff" },
  { scenario: "Your office is hosting a 'casual Friday' but you took it too far and wore dinosaur pajamas to meet the CEO.", category: "Sartorial Crises" },
  { scenario: "You are hired to do social media for a highly aggressive, anti-human garbage disposal company. Write your first tweet.", category: "Vicious Branding" },
  { scenario: "You accidentally deleted the entire company database. Write the apology email using only corporate buzzwords.", category: "Operational Blunders" },
  { scenario: "You are leading a slideshow presentation, but every single slide is just different close-ups of your cat yawn.", category: "Keynote Speeches" },
  { scenario: "You have to explain to your tech-support team why your keyboard is currently filled with hot, cooked oatmeal.", category: "Technical Difficulties" },
  { scenario: "Your company is trying to cut costs by replacing all coffee with lukewarm chamomile tea and positive affirmations.", category: "Thrift Operations" },
  { scenario: "You are a tech founder pitching an app that charges people $5 every time they check their phone in the bathroom.", category: "Potty Profits" },
  { scenario: "You need to explain to HR why you brought a highly complex, 4-foot-tall cotton candy machine to your desk.", category: "Sweet Stations" },
  { scenario: "Your manager asks you to 'synergize your core deliverables', but you have no idea what your actual job title is.", category: "Corporate Vagueness" },
  { scenario: "You are stuck in a video meeting but your camera is frozen with your face looking like you just swallowed a wasp.", category: "Digital Freezes" },
  { scenario: "Your company's new motto is incredibly confusing and sounds like a spell from Harry Potter. Pitch it to the public.", category: "Marketing Spells" },
  { scenario: "You accidentally brought your pet ferret to a high-stakes tech merger meeting. Ferret goes on the conference table.", category: "Wild Negotiators" },
  { scenario: "You are trying to negotiate a raise by telling your boss that you are currently being scouted by an elite spy agency.", category: "Leverage Tactics" },

  // --- MYTHICAL & SUPERNATURAL ---
  { scenario: "You have to convince a dragon that your collection of shiny tin can lids is actually a rare, highly valuable elven coin stash.", category: "Dragon Deals" },
  { scenario: "A vampire is refusing to bite you because they say your blood tastes like 'cheap energy drinks and instant noodles'.", category: "Choosy Vampires" },
  { scenario: "You accidentally summoned a minor demon whose only power is making all your socks slightly damp. Negotiate a peace treaty.", category: "Soggy Summoning" },
  { scenario: "You are a ghost trying to haunt a house, but the current owners are so loud and annoying that they are actually haunting you.", category: "Roaring Residents" },
  { scenario: "A wizard turned your legs into two giant pool noodles. How do you participate in a high-stakes track-and-field meet?", category: "Sponge Athletics" },
  { scenario: "The Grim Reaper arrives for you, but you can escape if you beat him in a game of competitive Connect Four.", category: "High-Stakes Checkers" },
  { scenario: "You accidentally drank a wizard's potion that makes you speak only in dramatic, deep-voiced movie trailer quotes.", category: "Vocal Magic" },
  { scenario: "You are a werewolf, but your transformation only happens when you look at a picture of a very cute, fluffy bunny.", category: "Lupine Flaws" },
  { scenario: "You are trying to sell fire insurance to a legendary, highly defensive phoenix who regularly bursts into flames.", category: "Fiery Policies" },
  { scenario: "A leprechaun offers you a pot of gold, but instead of coins, it's filled with garlic bread. Pitch why this is a massive upgrade.", category: "Savory Treasures" },
  { scenario: "You are a mermaid, but instead of a beautiful fish tail, you have the lower half of an incredibly grumpy sea cucumber.", category: "Murky Depths" },
  { scenario: "You have accidentally offended the god of thunder. To apologize, you must offer him a very fancy, homemade fruit basket.", category: "Deity Pacification" },
  { scenario: "A yeti bursts into your ski lodge and wants to borrow your hair dryer to style his majestic, frozen chest fur.", category: "Alpine Stylists" },
  { scenario: "You are trying to convince a group of angry centaurs that your bicycle is a highly advanced, mechanical cyber-horse.", category: "Centaurs & Cycles" },
  { scenario: "You accidentally got your hand stuck in a legendary stone that was supposed to only release the true King of Albion.", category: "Ruler of the Realm" },
  { scenario: "A group of hyper-intelligent gargoyles is judging your choice of casual streetwear from their cathedral perch.", category: "Gargoyle Fashion" },
  { scenario: "You are a goblin merchant trying to sell a completely flat, deflated football to a group of gullible forest elves.", category: "Goblin Bazaar" },
  { scenario: "You have to explain to a genie why your first wish is to have a lifetime supply of perfectly crispy waffle fries.", category: "Savory Wishes" },
  { scenario: "A woodland fairy has cursed you so that you can only walk by skipping sideways while whistling circus music.", category: "Fairy Curses" },
  { scenario: "You accidentally bought a haunted house where the ghost is a very enthusiastic, highly critical interior designer.", category: "Frightening Fixtures" },

  // --- RANDOM & STUPID ---
  { scenario: "You must convince a jury that your client is innocent of stealing 500 hams because he was 'conducting a science experiment'.", category: "Legal Defense" },
  { scenario: "You have been hired as a professional queue stander. What is your strategy to keep your spot from aggressive grandmas?", category: "Line Warfare" },
  { scenario: "You accidentally invented a bicycle that only rolls backwards. Pitch the health benefits of this revolutionary machine.", category: "Retro-Rolling" },
  { scenario: "You are trying to explain the rules of professional rock-paper-scissors to a highly confused group of martial artists.", category: "Fist Tactics" },
  { scenario: "You accidentally glued your own hand to your forehead. How do you explain this as a highly sophisticated fashion statement?", category: "Forehead Glues" },
  { scenario: "You are trying to win a global hide-and-seek tournament by hiding inside a giant fake wedge of cheddar cheese.", category: "Dairy Stealth" },
  { scenario: "You must convince your friends that your terrible, scratchy throat singing is actually an ancient form of meditation.", category: "Chanting Errors" },
  { scenario: "You are hired to write the instruction manual for a cardboard box. Describe its primary, highly advanced features.", category: "Package Genius" },
  { scenario: "You accidentally got your head stuck inside a decorative banister in a very busy, highly public library stairwell.", category: "Reader Obstacles" },
  { scenario: "You are trying to sell a premium bag of organic air to a hipster in Brooklyn. What are the scent notes of the air?", category: "Atmosphere Merchants" },
  { scenario: "You must explain to a police officer why your car's steering wheel is actually a giant plate of hard sourdough bread.", category: "Bready Driving" },
  { scenario: "You are running a marathon, but you are wearing a full, heavy metal suit of knight's armor. What is your survival plan?", category: "Chivalrous Running" },
  { scenario: "You accidentally ordered 5,000 blank postcards. What is your genius business strategy to sell them as 'mystery messages'?", category: "Creative Mailing" },
  { scenario: "You are trying to convince a very serious art gallery that your spilled cup of coffee on the floor is a masterpiece valued at $2M.", category: "Modern Art Follies" },
  { scenario: "You must write a review for a spoon that is slightly too flat to hold any soup. Make it sound like a beautiful luxury feature.", category: "Flat Utensils" },
  { scenario: "You accidentally dyed your hair hot green right before your very formal royal gala presentation. Spin the trend.", category: "Gala Glamour" },
  { scenario: "You are trying to teach your grandmother how to do a backflip onto a trampoline. Describe your safety philosophy.", category: "Elders & Acrobatics" },
  { scenario: "You must convince a flight attendant that your emotional support animal is a very large, highly defensive honey badger.", category: "Flight Security" },
  { scenario: "You accidentally swapped your suitcase with a professional magician's, and now your briefcase contains 4 white rabbits and a silk scarf.", category: "Magical Baggage" },
  { scenario: "You are trying to win a game of poker using only monopoly money and an extremely confident, unblinking staring contest pattern.", category: "Table Bluffing" },

  // --- ADULTING & EXISTENTIAL ---
  { scenario: "You are trying to explain to your bank why you spent $400 on custom, hand-knitted sweaters for your lizards.", category: "Financial Responsibility" },
  { scenario: "You need to explain to a group of 5-year-olds why doing taxes is actually a fun, thrilling real-life video game.", category: "Filing Fun" },
  { scenario: "You accidentally bought a car that only plays polka music at full volume when you indicate left. What's your maneuver plan?", category: "Polka Indicators" },
  { scenario: "You are trying to assemble a very complicated flat-pack desk, but the instructions are only in highly confusing hieroglyphics.", category: "Furniture Assembly" },
  { scenario: "You have to explain to your landlord why there is a giant, fully functional sand dune in the middle of your living room.", category: "Indoor Oasis" },
  { scenario: "You accidentally wore two completely different shoes to a very high-stakes job interview. Describe your explanation.", category: "Asymmetric Runway" },
  { scenario: "You need to convince your insurance company that a flock of runaway ostriches is responsible for the dents in your roof.", category: "Wildlife Claims" },
  { scenario: "You are writing a self-help book for people who have a crippling, dark fear of very loud, aggressive toast pops.", category: "Crusty Phobias" },
  { scenario: "You accidentally joined a highly competitive, professional lawn-mowing league. What is your team's intimidating rally cry?", category: "Lawn Masters" },
  { scenario: "You must explain to your spouse why you traded our family car for a giant, vintage cotton candy machine.", category: "Sweet Investments" },
  { scenario: "You are at a library and your phone starts loudly playing a high-pitch version of the crazy frog theme. Defend yourself.", category: "Library Incidents" },
  { scenario: "You accidentally got your tie stuck in the paper shredder during a high-stakes board presentation. Keep presenting.", category: "Executive Shreds" },
  { scenario: "You are trying to convince your dentist that your cavities are actually 'antique ivory deposits' that should be preserved.", category: "Dental Histories" },
  { scenario: "You must explain to your gym trainer why your water bottle is currently filled with hot, creamy cheddar soup.", category: "Liquid Nutrition" },
  { scenario: "You accidentally signed up for a 10k run thinking it was a 10k video game tournament. You are at the starting line.", category: "Accidental Olympians" },
  { scenario: "You need to write a letter of resignation using only references to different types of highly expensive cheeses.", category: "Gouda Goodbyes" },
  { scenario: "You are trapped in a conversations with a guy who claims that his uncle invented the question mark. How do you argue?", category: "Punctuation Disputes" },
  { scenario: "You have to convince your boss that taking a 3-hour nap on your desk is actually an intensive productivity ritual.", category: "Corporate Sleeping" },
  { scenario: "You accidentally bought a smart-watch that insults your fitness levels every time you sit down to eat a cookie.", category: "Wearable Insults" },
  { scenario: "You are writing a review for a restaurant whose only menu item is 'Slightly Warm Microwaved Soup'. Defend the minimalism.", category: "Hot Bowls" }
];
