/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Challenge } from "./types.js";

export const SPICY_PROMPTS: Challenge[] = [

{ scenario: "Hitler's sister was called _____ and she had a wild reputation.", category: "Alternative History" },
{ scenario: "The new Donald Trump rap album features a track called \"_____\".", category: "Political Roast" },
{ scenario: "What's the best way to solve world hunger? _____.", category: "Bad Solutions" },
{ scenario: "In the year 2030, the President of the United States will be _____.", category: "Future Predictions" },
{ scenario: "My ex-girlfriend's OnlyFans is just hours of _____.", category: "Romance Fails" },
{ scenario: "The real reason the Nazis lost WWII was _____.", category: "Alternative History" },
{ scenario: "What's hiding in Kim Jong-un's pants? _____.", category: "Classified Secrets" },
{ scenario: "The most racist thing I've ever said to a _____ is _____.", category: "Pure Offensive" },
{ scenario: "Adolf Hitler walks into a bar and orders _____.", category: "Bar Jokes" },
{ scenario: "The secret ingredient in McDonald's special sauce is _____.", category: "Fast Food Secrets" },
{ scenario: "Why do black guys have big dicks? _____.", category: "Anatomical Mysteries" },
{ scenario: "The new iPhone 18 will come with built-in _____.", category: "Apple Specs" },
{ scenario: "My therapist says my biggest issue is _____.", category: "Shrunk Talk" },
{ scenario: "What really happened on Epstein's island? _____.", category: "Conspiracy Theories" },
{ scenario: "The best way to get a promotion at work is _____.", category: "Career Ladder" },
{ scenario: "Hitler's favorite sex position was _____.", category: "Dictator Fantasies" },
{ scenario: "What's the difference between a Jew and a pizza? _____.", category: "Edgy Riddle" },
{ scenario: "In the apocalypse, I'll survive by _____.", category: "Survival Strategy" },
{ scenario: "The real Deep State is controlled by _____.", category: "Conspiracy Theories" },
{ scenario: "My Tinder date ended when she saw my _____.", category: "Dating Disasters" },
{ scenario: "The most offensive Halloween costume is _____.", category: "Costume Crimes" },
{ scenario: "Why can't you fool an Indian? _____.", category: "Edgy Riddle" },
{ scenario: "The Pope's hidden fetish is _____.", category: "Classified Secrets" },
{ scenario: "What gets me rock hard instantly? _____.", category: "Spicy After Dark" },
{ scenario: "Hitler's bunker had a secret room for _____.", category: "Alternative History" },
{ scenario: "The reason cats are superior to dogs is _____.", category: "Animal Incidents" },
{ scenario: "What's in my mom's search history? _____.", category: "Family Secrets" },
{ scenario: "The new mandatory school curriculum includes lessons on _____.", category: "School Daze" },
{ scenario: "Why do Asians suck at driving? _____.", category: "Edgy Riddle" },
{ scenario: "My family reunion turned into an orgy when _____.", category: "Family Secrets" },
{ scenario: "The cure for cancer is _____.", category: "Bad Solutions" },
{ scenario: "What's the whitest thing ever? _____.", category: "Cultural Observations" },
{ scenario: "Donald Trump's next wife will be _____.", category: "Political Roast" },
{ scenario: "The smell of my balls after a long day is _____.", category: "Anatomical Mysteries" },
{ scenario: "What Hitler and I have in common is _____.", category: "Dictator Fantasies" },
{ scenario: "The best way to smuggle drugs across the border is _____.", category: "Legal Trouble" },
{ scenario: "Why can't black people swim? _____.", category: "Edgy Riddle" },
{ scenario: "My biggest regret in life is _____.", category: "Life Stages" },
{ scenario: "The ghost in my house keeps demanding _____.", category: "Supernatural Shenanigans" },
{ scenario: "The real reason the Titanic sank was _____.", category: "Alternative History" },
{ scenario: "What do you call a Jewish superhero? _____.", category: "Edgy Riddle" },
{ scenario: "The most fucked up thing I've jerked off to is _____.", category: "Spicy After Dark" },
{ scenario: "Hitler's final words before dying were _____.", category: "Dictator Fantasies" },
{ scenario: "What's always in a Mexican's trunk? _____.", category: "Cultural Observations" },
{ scenario: "The next pandemic will be caused by _____.", category: "Future Predictions" },
{ scenario: "Why women belong in the kitchen: _____.", category: "Controversial Opinions" },
{ scenario: "My grandfather's war stories are actually about _____.", category: "Alternative History" },
{ scenario: "The secret to a happy marriage is _____.", category: "Relationship Wisdom" },
{ scenario: "What ruined my childhood? _____.", category: "Life Stages" },
{ scenario: "The most powerful black man alive is _____.", category: "Cultural Observations" },
{ scenario: "What happens in Vegas stays in _____.", category: "Vegas Stories" },
{ scenario: "Hitler's favorite Disney princess was _____.", category: "Dictator Fantasies" },
{ scenario: "Why do Indians smell like curry? _____.", category: "Edgy Riddle" },
{ scenario: "The thing that turns me gay for 5 minutes is _____.", category: "Spicy After Dark" },
{ scenario: "The best use for a dead hooker is _____.", category: "Pure Offensive" },
{ scenario: "What my boss really does in his office: _____.", category: "Office Life" },
{ scenario: "What's worse than finding a worm in your apple? _____.", category: "Edgy Riddle" },
{ scenario: "The next Holocaust will target _____.", category: "Pure Offensive" },
{ scenario: "My safe word is _____.", category: "Spicy After Dark" },
{ scenario: "The most racist children's book is called _____.", category: "Pure Offensive" },
{ scenario: "Why Chinese people are good at math: _____.", category: "Cultural Observations" },
{ scenario: "The real Illuminati meeting involves _____.", category: "Conspiracy Theories" },
{ scenario: "What I would do with a time machine and Hitler: _____.", category: "Alternative History" },
{ scenario: "The sluttiest thing my mom ever did was _____.", category: "Family Secrets" },
{ scenario: "What's growing in my foreskin? _____.", category: "Anatomical Mysteries" },
{ scenario: "The best thing about being white is _____.", category: "Cultural Observations" },
{ scenario: "Trump's wall was actually meant to keep out _____.", category: "Political Roast" },
{ scenario: "My suicide note will mention _____.", category: "Dark Confessions" },
{ scenario: "Why Jews control the banks: _____.", category: "Conspiracy Theories" },
{ scenario: "The most disturbing thing in my browser history is _____.", category: "Dark Confessions" },
{ scenario: "Hitler's OnlyFans username would be _____.", category: "Dictator Fantasies" },
{ scenario: "What black people do when the power goes out: _____.", category: "Cultural Observations" },
{ scenario: "The reason I can't get a girlfriend is _____.", category: "Dating Disasters" },
{ scenario: "The next Marvel movie will feature _____ as the villain.", category: "Entertainment Fails" },
{ scenario: "What's in the Vatican secret archives? _____.", category: "Classified Secrets" },
{ scenario: "The most offensive joke I know starts with _____.", category: "Pure Offensive" },
{ scenario: "Why Mexicans are always late: _____.", category: "Cultural Observations" },
{ scenario: "My bucket list includes _____.", category: "Final Words" },
{ scenario: "The real reason dinosaurs went extinct was _____.", category: "Junk Science" },
{ scenario: "What turns a feminist into a housewife? _____.", category: "Controversial Opinions" },
{ scenario: "Hitler's awkward teenage phase involved _____.", category: "Dictator Fantasies" },
{ scenario: "The smell of poverty is _____.", category: "Cultural Observations" },
{ scenario: "What's the best part of sex with a trans person? _____.", category: "Spicy After Dark" },
{ scenario: "The UN's real purpose is _____.", category: "Conspiracy Theories" },
{ scenario: "Why Asians can't hold their liquor: _____.", category: "Cultural Observations" },
{ scenario: "My darkest fantasy is _____.", category: "Spicy After Dark" },
{ scenario: "The thing that will get me canceled is _____.", category: "Dark Confessions" },
{ scenario: "What Santa brings to the ghetto on Christmas: _____.", category: "Cultural Observations" },
{ scenario: "Hitler's spirit animal is _____.", category: "Dictator Fantasies" },
{ scenario: "The most overrated thing in the world is _____.", category: "Controversial Opinions" },
{ scenario: "Why white girls love BBC: _____.", category: "Spicy After Dark" },
{ scenario: "The secret menu item at Chick-fil-A is _____.", category: "Fast Food Secrets" },
{ scenario: "What I would sell my soul for: _____.", category: "Dark Confessions" },
{ scenario: "The best way to hide a body is _____.", category: "True Crime Lite" },
{ scenario: "My therapist's reaction when I told her about _____.", category: "Shrunk Talk" },
{ scenario: "The reason the British have bad teeth is _____.", category: "Cultural Observations" },
{ scenario: "What's always wet and ready? _____.", category: "Spicy After Dark" },
{ scenario: "The final boss of life is _____.", category: "Game Night Disasters" },
{ scenario: "The new global currency will be backed by _____.", category: "Future Predictions" },
{ scenario: "What my dog does when I'm not home: _____.", category: "Animal Incidents" },
{ scenario: "Hitler's pickup line was _____.", category: "Dictator Fantasies" },
{ scenario: "Why can't you trust a black doctor? _____.", category: "Pure Offensive" },
{ scenario: "The most illegal thing I've done sober is _____.", category: "Legal Trouble" },
{ scenario: "My family heirloom is actually _____.", category: "Family Secrets" },
{ scenario: "The pyramids were built by _____.", category: "Alternative History" },
{ scenario: "What's in Elon Musk's sex dungeon? _____.", category: "Classified Secrets" },
{ scenario: "The sluttiest celebrity is _____ because _____.", category: "Spicy After Dark" },
{ scenario: "Why do rednecks marry their cousins? _____.", category: "Cultural Observations" },
{ scenario: "The next thing I want to put in my ass is _____.", category: "Spicy After Dark" },
{ scenario: "Hitler's favorite fast food order was _____.", category: "Dictator Fantasies" },
{ scenario: "What Jews do on Yom Kippur when no one's looking: _____.", category: "Cultural Observations" },
{ scenario: "The best cure for depression is _____.", category: "Bad Solutions" },
{ scenario: "Why women fake orgasms: _____.", category: "Relationship Wisdom" },
{ scenario: "The real moon landing footage shows _____.", category: "Conspiracy Theories" },
{ scenario: "My search for \"_____ porn\" is concerning.", category: "Dark Confessions" },
{ scenario: "The most racist country on Earth is _____.", category: "Pure Offensive" },
{ scenario: "What happens at furry conventions after dark: _____.", category: "Spicy After Dark" },
{ scenario: "Trump's secret plan for world domination involves _____.", category: "Political Roast" },
{ scenario: "The reason I have trust issues is _____.", category: "Life Stages" },
{ scenario: "What's black and screams? _____.", category: "Edgy Riddle" },
{ scenario: "Hitler's art school rejection letter mentioned _____.", category: "Alternative History" },
{ scenario: "The thing that makes me racist is _____.", category: "Dark Confessions" },
{ scenario: "Why Indians can't use toilets properly: _____.", category: "Cultural Observations" },
{ scenario: "My ideal threesome includes _____ and _____.", category: "Spicy After Dark" },
{ scenario: "The government hides the truth about _____.", category: "Conspiracy Theories" },
{ scenario: "The most fucked up family tradition I have is _____.", category: "Family Secrets" },
{ scenario: "What Santa Claus does to naughty kids: _____.", category: "Dark Confessions" },
{ scenario: "The best thing about being adopted is _____.", category: "Family Secrets" },
{ scenario: "Why black people love fried chicken: _____.", category: "Cultural Observations" },
{ scenario: "Hitler's time travel adventure would start with _____.", category: "Alternative History" },
{ scenario: "The secret to eternal life is _____.", category: "Bad Solutions" },
{ scenario: "What's the whitest crime? _____.", category: "Cultural Observations" },
{ scenario: "My boss caught me _____ at work.", category: "Office Life" },
{ scenario: "The real reason for circumcision is _____.", category: "Anatomical Mysteries" },
{ scenario: "Why Muslims can't draw Muhammad: _____.", category: "Cultural Observations" },
{ scenario: "The most offensive baby name is _____.", category: "Pure Offensive" },
{ scenario: "What I would do during a purge: _____.", category: "Survival Strategy" },
{ scenario: "The thing growing in my basement is _____.", category: "Home Horrors" },
{ scenario: "Trump's next tweet will be about _____.", category: "Political Roast" },
{ scenario: "Why Asians are bad at sports: _____.", category: "Cultural Observations" },
{ scenario: "My suicide method of choice is _____.", category: "Dark Confessions" },
{ scenario: "The Vatican pedophile ring is run by _____.", category: "Conspiracy Theories" },
{ scenario: "What's funnier than a dead baby? _____.", category: "Pure Offensive" },
{ scenario: "Hitler's favorite rap battle opponent was _____.", category: "Dictator Fantasies" },
{ scenario: "The reason for male pattern baldness is _____.", category: "Junk Science" },
{ scenario: "What my girlfriend does with her exes: _____.", category: "Romance Fails" },
{ scenario: "Why can't white people dance? _____.", category: "Cultural Observations" },
{ scenario: "The real reason aliens won't visit Earth is _____.", category: "Cosmic Regrets" },
{ scenario: "Kim Kardashian's next sex tape will feature _____.", category: "Spicy After Dark" },
{ scenario: "What's the best way to cheat on your wife? _____.", category: "Relationship Wisdom" },
{ scenario: "My grandma's only regret in life is _____.", category: "Life Stages" },
{ scenario: "The secret menu at Area 51 serves _____.", category: "Classified Secrets" },
{ scenario: "Why do white people love hiking? _____.", category: "Cultural Observations" },
{ scenario: "Hitler's secret twin brother specialized in _____.", category: "Alternative History" },
{ scenario: "The most inappropriate funeral song is _____.", category: "Dying Arts" },
{ scenario: "What's hiding under my bed after dark? _____.", category: "Supernatural Shenanigans" },
{ scenario: "Elon Musk's next child will be named _____.", category: "Future Predictions" },
{ scenario: "The cure for erectile dysfunction is _____.", category: "Medical Mysteries" },
{ scenario: "Why Puerto Ricans love reggaeton: _____.", category: "Cultural Observations" },
{ scenario: "My autopsy will reveal traces of _____.", category: "Dark Confessions" },
{ scenario: "The sluttiest thing at Burning Man is _____.", category: "Spicy After Dark" },
{ scenario: "What's always sticky in a crackhead's pocket? _____.", category: "Pure Offensive" },
{ scenario: "The next viral TikTok challenge involves _____.", category: "Tech Problems" },
{ scenario: "Hitler's retirement plan included _____.", category: "Alternative History" },
{ scenario: "Why can't you trust Italians with money? _____.", category: "Cultural Observations" },
{ scenario: "My dark web purchase turned out to be _____.", category: "Legal Trouble" },
{ scenario: "The smell of my ex's bedroom is _____.", category: "Romance Fails" },
{ scenario: "What happens in North Korean prisons after lights out: _____.", category: "Classified Secrets" },
{ scenario: "The best way to dispose of evidence is _____.", category: "True Crime Lite" },
{ scenario: "My therapist's notes on me mention _____.", category: "Shrunk Talk" },
{ scenario: "Why fat people can't stop eating: _____.", category: "Controversial Opinions" },
{ scenario: "The real power behind Big Pharma is _____.", category: "Conspiracy Theories" },
{ scenario: "Trump's secret porn stash contains _____.", category: "Political Roast" },
{ scenario: "What's the fastest way to get deported? _____.", category: "Legal Trouble" },
{ scenario: "The thing growing in my neighbor's crawlspace is _____.", category: "Neighbor Nightmares" },
{ scenario: "Why do Arabs love camels? _____.", category: "Edgy Riddle" },
{ scenario: "My bucket list's top item is experiencing _____.", category: "Dark Confessions" },
{ scenario: "The most disturbing kids' show character is _____.", category: "Entertainment Fails" },
{ scenario: "Hitler's favorite late-night snack was _____.", category: "Dictator Fantasies" },
{ scenario: "What's in the FBI's blackmail files on celebrities? _____.", category: "Classified Secrets" },
{ scenario: "The reason I ghosted my last date: _____.", category: "Dating Disasters" },
{ scenario: "Why rednecks shoot guns at stop signs: _____.", category: "Cultural Observations" },
{ scenario: "My sleep paralysis demon looks like _____.", category: "Supernatural Shenanigans" },
{ scenario: "The next cryptocurrency crash will be caused by _____.", category: "Future Predictions" },
{ scenario: "What's worse than blue balls? _____.", category: "Anatomical Mysteries" },
{ scenario: "The secret ingredient in prison wine is _____.", category: "Classified Secrets" },
{ scenario: "Why Japanese people live so long: _____.", category: "Junk Science" },
{ scenario: "My Tinder bio should have mentioned _____.", category: "Dating Disasters" },
{ scenario: "The most fucked up thing at Coachella: _____.", category: "Festival Fails" },
{ scenario: "Hitler's ghost still haunts _____.", category: "Supernatural Shenanigans" },
{ scenario: "What my boss jerks off to during meetings: _____.", category: "Office Life" },
{ scenario: "The best way to win an argument with your girlfriend: _____.", category: "Relationship Wisdom" },
{ scenario: "Why do Mexicans make great gardeners? _____.", category: "Cultural Observations" },
{ scenario: "The contents of Jeffrey Epstein's hard drive include _____.", category: "Classified Secrets" },
{ scenario: "My midlife crisis involves buying _____.", category: "Life Stages" },
{ scenario: "What's black and blue and hates cops? _____.", category: "Edgy Riddle" },
{ scenario: "The real reason the pyramids have hidden chambers: _____.", category: "Alternative History" },
{ scenario: "Why can't white people handle spicy food? _____.", category: "Cultural Observations" },
{ scenario: "The sluttiest teacher at my school was into _____.", category: "School Daze" },
{ scenario: "Trump's post-presidency business venture is _____.", category: "Political Roast" },
{ scenario: "What's always in a trailer park fridge? _____.", category: "Cultural Observations" },
{ scenario: "My family secret recipe contains _____.", category: "Family Secrets" },
{ scenario: "The next celebrity to get canceled for _____ is _____.", category: "Entertainment Fails" },
{ scenario: "Hitler's awkward boner during the Olympics: _____.", category: "Dictator Fantasies" },
{ scenario: "Why do black guys sag their pants? _____.", category: "Cultural Observations" },
{ scenario: "The smell after a gangbang is _____.", category: "Spicy After Dark" },
{ scenario: "My suicide letter will start with _____.", category: "Dark Confessions" },
{ scenario: "The most racist Olympic sport is _____.", category: "Pure Offensive" },
{ scenario: "What's growing in Kim Jong-un's nuclear bunker? _____.", category: "Classified Secrets" },
{ scenario: "The best part about being homeless is _____.", category: "Dark Confessions" },
{ scenario: "Why Indians are great at coding: _____.", category: "Cultural Observations" },
{ scenario: "My ex's nudes are now being used for _____.", category: "Romance Fails" },
{ scenario: "The secret handshake of the elite involves _____.", category: "Conspiracy Theories" },
{ scenario: "What's funnier than a dead baby joke? _____.", category: "Pure Offensive" },
{ scenario: "Hitler's favorite porn category was _____.", category: "Dictator Fantasies" },
{ scenario: "The reason for my trust fund baby's behavior: _____.", category: "Life Stages" },
{ scenario: "Why do feminists hate mirrors? _____.", category: "Controversial Opinions" },
{ scenario: "The most illegal family vacation memory: _____.", category: "Family Secrets" },
{ scenario: "My search history's darkest corner has _____.", category: "Dark Confessions" },
{ scenario: "What's in Putin's private zoo? _____.", category: "Classified Secrets" },
{ scenario: "The best way to fake your own death: _____.", category: "True Crime Lite" },
{ scenario: "Why Asians dominate esports: _____.", category: "Cultural Observations" },
{ scenario: "The thing that makes me finish instantly is _____.", category: "Spicy After Dark" },
{ scenario: "My grandfather's war trophy was actually _____.", category: "Alternative History" },
{ scenario: "The next thing banned by the government: _____.", category: "Future Predictions" },
{ scenario: "What's always screaming in the ghetto? _____.", category: "Cultural Observations" },
{ scenario: "Hitler's time machine would be used for _____.", category: "Alternative History" },
{ scenario: "The sluttiest thing my sister did in college: _____.", category: "Family Secrets" },
{ scenario: "Why can't you trust a lawyer? _____.", category: "Legal Trouble" },
{ scenario: "My ideal apocalypse partner is _____.", category: "Survival Strategy" },
{ scenario: "The secret to perfect fried chicken: _____.", category: "Fast Food Secrets" },
{ scenario: "What's in the Queen's hidden vault? _____.", category: "Classified Secrets" },
{ scenario: "The most offensive emoji combination is _____.", category: "Pure Offensive" },
{ scenario: "Why do white girls twerk to trap music? _____.", category: "Cultural Observations" },
{ scenario: "My boss's HR complaint against me was for _____.", category: "Office Life" },
{ scenario: "The reason dinosaurs really went extinct: _____.", category: "Junk Science" },
{ scenario: "What's wetter than the ocean? _____.", category: "Spicy After Dark" },
{ scenario: "Hitler's favorite video game character: _____.", category: "Dictator Fantasies" },
{ scenario: "The best use for a glory hole is _____.", category: "Spicy After Dark" },
{ scenario: "Why Muslims love beards: _____.", category: "Cultural Observations" },
{ scenario: "My dark fantasy about my stepsister: _____.", category: "Spicy After Dark" },
{ scenario: "The next pandemic will start in _____.", category: "Future Predictions" },
{ scenario: "What's always in a pimp's trunk? _____.", category: "True Crime Lite" },
{ scenario: "The real Illuminati ritual involves _____.", category: "Conspiracy Theories" },
{ scenario: "Why can't black people get sunburned? _____.", category: "Edgy Riddle" },
{ scenario: "My therapist quit after hearing about _____.", category: "Shrunk Talk" },
{ scenario: "The most fucked up carnival game prize: _____.", category: "Party Fails" },
{ scenario: "Trump's next golf course will be built on _____.", category: "Political Roast" },
{ scenario: "What's black and red and screams all night? _____.", category: "Edgy Riddle" },
{ scenario: "The reason I failed my drug test: _____.", category: "Legal Trouble" },
{ scenario: "Why do Jews love diamonds? _____.", category: "Cultural Observations" },
{ scenario: "My suicide note's punchline is _____.", category: "Dark Confessions" },
{ scenario: "The sluttiest nun in history was known for _____.", category: "Pure Offensive" },
{ scenario: "What's hiding in my landlord's basement? _____.", category: "Home Horrors" },
{ scenario: "The best revenge on an ex is _____.", category: "Romance Fails" },
{ scenario: "Why Asians are bad at basketball: _____.", category: "Cultural Observations" },
{ scenario: "Hitler's pickup line at the bar: _____.", category: "Dictator Fantasies" },
{ scenario: "The secret menu at McDonald's for degenerates is _____.", category: "Fast Food Secrets" },
{ scenario: "My family reunion's hidden activity: _____.", category: "Family Secrets" },
{ scenario: "What's the whitest music genre? _____.", category: "Cultural Observations" },
{ scenario: "The next cult leader will worship _____.", category: "Conspiracy Theories" },
{ scenario: "Why rednecks love monster trucks: _____.", category: "Cultural Observations" },
{ scenario: "My browser history after a breakup: _____.", category: "Romance Fails" },
{ scenario: "The most disturbing thing found in Hitler's diary: _____.", category: "Alternative History" },
{ scenario: "What's always sticky on a porn set? _____.", category: "Spicy After Dark" },
{ scenario: "The reason for my micropenis: _____.", category: "Anatomical Mysteries" },
{ scenario: "Why do Mexicans cross the border? _____.", category: "Controversial Opinions" },
{ scenario: "The elite's favorite sacrifice ritual: _____.", category: "Conspiracy Theories" },
{ scenario: "My ideal death involves _____.", category: "Final Words" },
{ scenario: "The sluttiest thing at a bachelor party: _____.", category: "Wedding Chaos" },
{ scenario: "What's in Bill Gates' bunker? _____.", category: "Classified Secrets" },
{ scenario: "Why can't you trust vegans? _____.", category: "Controversial Opinions" },
{ scenario: "Hitler's favorite meme would be _____.", category: "Dictator Fantasies" },
{ scenario: "The best way to smuggle immigrants: _____.", category: "Legal Trouble" },
{ scenario: "My darkest secret about my pet: _____.", category: "Animal Incidents" },
{ scenario: "The reason the stock market crashes: _____.", category: "Conspiracy Theories" },
{ scenario: "What's funnier than cancer? _____.", category: "Pure Offensive" },
{ scenario: "The next viral deepfake features _____.", category: "Tech Problems" },
{ scenario: "Why do black women have attitudes? _____.", category: "Cultural Observations" },
{ scenario: "My therapist's hidden fetish: _____.", category: "Shrunk Talk" },
{ scenario: "The most offensive baby shower gift: _____.", category: "Pure Offensive" },
{ scenario: "What's always in a crack whore's purse? _____.", category: "Pure Offensive" },
{ scenario: "Trump's secret Twitter burner account posts about _____.", category: "Political Roast" },
{ scenario: "The pyramid scheme that actually works: _____.", category: "Bad Advice" },
{ scenario: "Why Indians shit in the street: _____.", category: "Cultural Observations" },
{ scenario: "My bucket list's most illegal item: _____.", category: "Dark Confessions" },
{ scenario: "The real reason for chemtrails: _____.", category: "Conspiracy Theories" },
{ scenario: "Hitler's awkward teenage wet dream: _____.", category: "Dictator Fantasies" },
{ scenario: "What's blacker than my ex's heart? _____.", category: "Romance Fails" },
{ scenario: "The best cure for blue balls: _____.", category: "Anatomical Mysteries" },
{ scenario: "Why white people apologize too much: _____.", category: "Cultural Observations" },
{ scenario: "My sleep paralysis demon demands _____.", category: "Supernatural Shenanigans" },
{ scenario: "The secret ingredient in hot dogs: _____.", category: "Fast Food Secrets" },
{ scenario: "What's growing in my nether regions after that hookup? _____.", category: "Medical Mysteries" },
{ scenario: "The most fucked up zoo exhibit: _____.", category: "Animal Incidents" },
{ scenario: "Why do Arabs wear robes? _____.", category: "Cultural Observations" },
{ scenario: "My ex's revenge porn stars _____.", category: "Romance Fails" },
{ scenario: "The next celebrity scandal involves _____.", category: "Entertainment Fails" },
{ scenario: "Hitler's favorite OnlyFans category: _____.", category: "Dictator Fantasies" },
{ scenario: "The reason I can't hold down a job: _____.", category: "Career Suicide" },
{ scenario: "What's always wet in a nursing home? _____.", category: "Pure Offensive" },
{ scenario: "The elite pedophile island's new location: _____.", category: "Conspiracy Theories" },
{ scenario: "Why Asians love tentacle porn: _____.", category: "Cultural Observations" },
{ scenario: "My family curse involves _____.", category: "Family Secrets" },
{ scenario: "The best way to start a race war: _____.", category: "Pure Offensive" },
{ scenario: "What's in my neighbor's sex dungeon? _____.", category: "Neighbor Nightmares" },
{ scenario: "Trump's next wife will be famous for _____.", category: "Political Roast" },
{ scenario: "The most disturbing carnival sideshow: _____.", category: "Party Fails" },
{ scenario: "Why can't white guys jump? _____.", category: "Cultural Observations" },
{ scenario: "My suicide attempt's funniest failure: _____.", category: "Dark Confessions" },
{ scenario: "The secret to eternal youth: _____.", category: "Bad Solutions" },
{ scenario: "Hitler's time in Argentina involved _____.", category: "Alternative History" },
{ scenario: "What's smellier than my gym bag? _____.", category: "Fitness Fails" },
{ scenario: "The next false flag operation: _____.", category: "Conspiracy Theories" },
{ scenario: "Why feminists need trigger warnings: _____.", category: "Controversial Opinions" },
{ scenario: "My darkest search term ever: _____.", category: "Dark Confessions" },
{ scenario: "The sluttiest thing at Comic-Con: _____.", category: "Festival Fails" },
{ scenario: "What's always screaming during fireworks? _____.", category: "Cultural Observations" },
{ scenario: "The reason for my porn addiction: _____.", category: "Dark Confessions" },
{ scenario: "Why do Jews run Hollywood? _____.", category: "Conspiracy Theories" },
{ scenario: "My ideal war crime: _____.", category: "Pure Offensive" },
{ scenario: "The best part about sleeping with a larger partner: _____.", category: "Spicy After Dark" },
{ scenario: "Hitler's favorite cartoon character: _____.", category: "Dictator Fantasies" },
{ scenario: "The contents of my repressed memories: _____.", category: "Dark Confessions" },
{ scenario: "Why Mexicans are great at construction: _____.", category: "Cultural Observations" },
{ scenario: "My boss's office \"meeting\" was actually _____.", category: "Office Life" },
{ scenario: "The next thing to be canceled forever: _____.", category: "Future Predictions" },
{ scenario: "What's in Putin's private bathroom? _____.", category: "Classified Secrets" },
{ scenario: "The most offensive wedding toast: _____.", category: "Wedding Chaos" },
{ scenario: "Why can't you trust a politician? _____.", category: "Legal Trouble" },
{ scenario: "My midlife crisis purchase of _____ was a mistake.", category: "Life Stages" },
{ scenario: "The secret recipe for meth involves _____.", category: "Pure Offensive" },
{ scenario: "Hitler's awkward family reunion: _____.", category: "Dictator Fantasies" },
{ scenario: "What's black and blue after date night? _____.", category: "Spicy After Dark" },
{ scenario: "The best use for a dead celebrity: _____.", category: "Pure Offensive" },
{ scenario: "Why Asians can't drive straight: _____.", category: "Cultural Observations" },
{ scenario: "My family heirloom's true purpose: _____.", category: "Family Secrets" },
{ scenario: "The real reason behind cancel culture: _____.", category: "Controversial Opinions" },
{ scenario: "What's always sticky in a glory hole? _____.", category: "Spicy After Dark" },
{ scenario: "The next pandemic's patient zero is _____.", category: "Future Predictions" },
{ scenario: "Why rednecks hate cities: _____.", category: "Cultural Observations" },
{ scenario: "My therapist's notes after our last session: _____.", category: "Shrunk Talk" },
{ scenario: "The sluttiest thing my mom did on vacation: _____.", category: "Family Secrets" },
{ scenario: "Hitler's favorite fast food combo: _____.", category: "Dictator Fantasies" },
{ scenario: "What's worse than a root canal? _____.", category: "Medical Mysteries" },
{ scenario: "The elite's favorite blackmail material: _____.", category: "Conspiracy Theories" },
{ scenario: "My final words before dying will be _____.", category: "Final Words" },

]