/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Challenge } from "./types.js";

export const SPICY_PROMPTS: Challenge[] = [
  
 
  { scenario: "Hitler's sister was called _____ and she had a wild reputation.", category: "Spicy After Dark" },
{ scenario: "The new Donald Trump rap album features a track called \"_____\".", category: "Political Roast" },
{ scenario: "What's the best way to solve world hunger? _____.", category: "Bad Solutions" },
{ scenario: "In the year 2030, the President of the United States will be _____.", category: "Future Predictions" },
{ scenario: "My ex-girlfriend's OnlyFans is just hours of _____.", category: "Ex-Files" },
{ scenario: "The real reason the Nazis lost WWII was _____.", category: "Alternative History" },
{ scenario: "What's hiding in Kim Jong-un's pants? _____.", category: "Classified Secrets" },
{ scenario: "The most racist thing I've ever said out loud was _____, and I stand by it.", category: "Pure Offensive" },
{ scenario: "Adolf Hitler walks into a bar and orders _____.", category: "Bar Jokes" },
{ scenario: "The secret ingredient in McDonald's special sauce is _____.", category: "Fast Food Secrets" },
{ scenario: "Scientists finally explained why black guys have big dicks. The answer? _____.", category: "Anatomical Mysteries" },
{ scenario: "The new iPhone 18 will come with built-in _____.", category: "Apple Specs" },
{ scenario: "My therapist says my biggest issue is _____.", category: "Shrunk Talk" },
{ scenario: "What really happened on Epstein's island? _____.", category: "Conspiracy Theories" },
{ scenario: "The best way to get a promotion at work is _____.", category: "Career Ladder" },
{ scenario: "Hitler's favorite sex position was called _____ and involved _____.", category: "Dictator Fantasies" },
{ scenario: "What's the difference between a Jew and a pizza? _____.", category: "Edgy Riddle" },
{ scenario: "In the apocalypse, I'll survive by _____.", category: "Survival Strategy" },
{ scenario: "The real Deep State is secretly controlled by _____.", category: "Conspiracy Theories" },
{ scenario: "My Tinder date ended when she saw my _____.", category: "Dating Disasters" },
{ scenario: "The most offensive Halloween costume anyone can wear: _____.", category: "Spicy After Dark" },
{ scenario: "Hitler's bunker had a secret room dedicated entirely to _____.", category: "Dictator Fantasies" },
{ scenario: "What's in my mom's search history? _____.", category: "Family Secrets" },
{ scenario: "The new mandatory school curriculum includes compulsory lessons on _____.", category: "School Daze" },
{ scenario: "My biggest regret in life is _____.", category: "Life Lessons" },
{ scenario: "The ghost in my house keeps demanding _____.", category: "Supernatural Shenanigans" },
{ scenario: "The real reason the Titanic sank was _____.", category: "Alternative History" },
{ scenario: "What do you call a Jewish superhero? _____.", category: "Edgy Riddle" },
{ scenario: "The most disturbing thing I've ever genuinely enjoyed watching is _____.", category: "Confessions" },
{ scenario: "Hitler's final words before dying in the bunker were _____.", category: "Dictator Fantasies" },
{ scenario: "The next pandemic will be caused by _____.", category: "Future Predictions" },
{ scenario: "My grandfather's war stories are actually about _____.", category: "Family Secrets" },
{ scenario: "The secret to a happy marriage is _____.", category: "Relationship Advice" },
{ scenario: "What ruined my childhood? _____.", category: "Confessions" },
{ scenario: "What happens in Vegas stays in _____, which is a problem.", category: "Vegas Stories" },
{ scenario: "Hitler's favorite Disney princess was _____ because _____.", category: "Dictator Fantasies" },
{ scenario: "The thing that turns me on for exactly 5 minutes is _____.", category: "Spicy After Dark" },
{ scenario: "What's worse than finding a worm in your apple? _____.", category: "Edgy Riddle" },
{ scenario: "The next global crisis will target _____.", category: "Future Predictions" },
{ scenario: "My safe word is _____ and I've had to use it twice this week.", category: "Spicy After Dark" },
{ scenario: "The most racist children's book ever printed was called '_____.'", category: "Pure Offensive" },
{ scenario: "The real Illuminati meeting always ends with _____.", category: "Conspiracy Theories" },
{ scenario: "The most disturbing thing in my browser history is _____.", category: "Confessions" },
{ scenario: "Hitler's OnlyFans username would be _____ and his pinned post would be _____.", category: "Dictator Fantasies" },
{ scenario: "The reason I can't get a girlfriend is definitely _____.", category: "Self-Roast" },
{ scenario: "What's in the Vatican's secret archives? _____.", category: "Classified Secrets" },
{ scenario: "My bucket list includes _____ before I die.", category: "Bucket List" },
{ scenario: "The real reason dinosaurs went extinct was _____.", category: "Alternative History" },
{ scenario: "Hitler's awkward teenage phase involved a deep obsession with _____.", category: "Dictator Fantasies" },
{ scenario: "The smell of poverty, according to scientists, is _____.", category: "Dark Observations" },
{ scenario: "The UN's actual secret purpose is _____.", category: "Conspiracy Theories" },
{ scenario: "My darkest fantasy involves _____ and I need you to not react.", category: "Confessions" },
{ scenario: "The thing that will eventually get me canceled is _____.", category: "Confessions" },
{ scenario: "Hitler's spirit animal is _____ and the resemblance is undeniable.", category: "Dictator Fantasies" },
{ scenario: "The most overrated thing in the entire world is _____.", category: "Hot Takes" },
{ scenario: "The secret menu item at every fast food chain is _____.", category: "Fast Food Secrets" },
{ scenario: "What I would sell my soul for, without hesitation: _____.", category: "Confessions" },
{ scenario: "The best way to hide a body is _____. Don't ask how I know.", category: "Dark Advice" },
{ scenario: "My therapist's exact reaction when I told her about _____ was to slowly close her notebook.", category: "Shrunk Talk" },
{ scenario: "What's always wet, always ready, and completely misunderstood? _____.", category: "Spicy After Dark" },
{ scenario: "The final boss of life is _____.", category: "Game Over" },
{ scenario: "The new global currency will be backed entirely by _____.", category: "Future Predictions" },
{ scenario: "What my dog does when I'm not home, according to the hidden camera: _____.", category: "Animal Incidents" },
{ scenario: "Hitler's pickup line was _____ and it worked every time.", category: "Dictator Fantasies" },
{ scenario: "The most illegal thing I've ever done while completely sober: _____.", category: "Confessions" },
{ scenario: "My family heirloom is actually _____. We don't talk about it.", category: "Family Secrets" },
{ scenario: "The pyramids were actually built by _____ and the evidence is overwhelming.", category: "Alternative History" },
{ scenario: "What's in Elon Musk's secret underground compound? _____.", category: "Classified Secrets" },
{ scenario: "The sluttiest celebrity alive is _____ and we all know why.", category: "Celebrity Roast" },
{ scenario: "Hitler's favorite fast food order was _____ with extra _____.", category: "Dictator Fantasies" },
{ scenario: "The best cure for depression, according to no licensed doctor, is _____.", category: "Bad Solutions" },
{ scenario: "The real moon landing footage that NASA won't release shows _____.", category: "Conspiracy Theories" },
{ scenario: "What's black and screams? _____.", category: "Edgy Riddle" },
{ scenario: "Hitler's art school rejection letter specifically mentioned _____.", category: "Alternative History" },
{ scenario: "The government has been hiding the truth about _____ for decades.", category: "Conspiracy Theories" },
{ scenario: "The most disturbing family tradition I inherited is _____.", category: "Family Secrets" },
{ scenario: "The best thing about being adopted is _____.", category: "Dark Observations" },
{ scenario: "Hitler's time travel adventure would begin with him immediately trying to _____.", category: "Dictator Fantasies" },
{ scenario: "The secret to eternal life involves _____ and you don't want to know the details.", category: "Conspiracy Theories" },
{ scenario: "What's the whitest crime ever committed? _____.", category: "Racial Observations" },
{ scenario: "My boss walked in and caught me _____ at my desk.", category: "Office Life" },
{ scenario: "The most offensive baby name a parent has ever given: _____.", category: "Pure Offensive" },
{ scenario: "What I would personally do during a purge: _____.", category: "Dark Confessions" },
{ scenario: "The thing currently growing in my basement is _____. It has a name now.", category: "Home Horrors" },
{ scenario: "The reason for male pattern baldness is actually _____.", category: "Junk Science" },
{ scenario: "What's funnier than a dead baby? _____.", category: "Too Dark" },
{ scenario: "Hitler's favorite rap battle opponent was _____ and he lost every time.", category: "Dictator Fantasies" },
{ scenario: "The reason for male pattern baldness, according to my grandmother, is _____.", category: "Old World Remedies" },
{ scenario: "Why can't white people dance? Scientists believe it's because of _____.", category: "Racial Observations" },
{ scenario: "The most suspicious thing my neighbor does at 3 AM is _____.", category: "Neighbor Nightmares" },
{ scenario: "The CIA's classified file on me includes the phrase '_____.'", category: "Classified Secrets" },
{ scenario: "My ex wife got the house, the car, and _____. I got _____.", category: "Divorce Court" },
{ scenario: "The world's worst terrorist plot involved _____.", category: "Too Dark" },
{ scenario: "My porn category of choice says a lot about me, specifically that I enjoy _____.", category: "Confessions" },
{ scenario: "The rejected name for the Holocaust was _____.", category: "Too Dark" },
{ scenario: "What Stalin and I have in common: _____.", category: "Dictator Comparisons" },
{ scenario: "The North Korean tourism brochure highlights _____ as their top attraction.", category: "Classified Secrets" },
{ scenario: "The most disturbing thing my Uber driver has ever said to me: '_____.'", category: "Awkward Rides" },
{ scenario: "My drug of choice isn't technically illegal, it's just _____.", category: "Confessions" },
{ scenario: "The worst possible safe word to choose is _____.", category: "Spicy After Dark" },
{ scenario: "Kim Jong-un's personal diary entry for Tuesday just reads: '_____.'", category: "Classified Secrets" },
{ scenario: "The thing I'm most ashamed of ordering on Amazon: _____.", category: "Confessions" },
{ scenario: "Jeffrey Epstein's flight log also includes a trip to _____ with _____.", category: "Too Dark" },
{ scenario: "My grandmother's secret recipe includes _____ and a troubling amount of _____.", category: "Family Secrets" },
{ scenario: "The most inappropriate thing to yell during a moment of silence: _____.", category: "Pure Offensive" },
{ scenario: "The world's worst pick-up line used exclusively at funerals: '_____.'", category: "Too Dark" },
{ scenario: "Bin Laden's search history would have included _____.", category: "Too Dark" },
{ scenario: "The real reason Area 51 is classified has nothing to do with aliens — it's _____.", category: "Conspiracy Theories" },
{ scenario: "My therapist started crying when I admitted that I _____.", category: "Shrunk Talk" },
{ scenario: "The leaked celebrity sex tape nobody expected featured _____.", category: "Celebrity Roast" },
{ scenario: "The most uncomfortable thing to discover about your Airbnb host: _____.", category: "Travel Nightmares" },
{ scenario: "What serial killers do in their spare time to unwind: _____.", category: "Too Dark" },
{ scenario: "The thing I do in private that would end my career instantly: _____.", category: "Confessions" },
{ scenario: "The next thing they'll put a trigger warning on is _____.", category: "Hot Takes" },
{ scenario: "My OnlyFans description simply reads: 'Come watch me _____.'", category: "Spicy After Dark" },
{ scenario: "The dumbest conspiracy theory I actually believe is that _____ is secretly _____.", category: "Conspiracy Theories" },
{ scenario: "Putin's personal kink is _____ and it explains a lot about foreign policy.", category: "Dictator Fantasies" },
{ scenario: "The one thing that unites all racists: _____.", category: "Dark Observations" },
{ scenario: "The worst thing to inherit from a deceased relative: _____.", category: "Family Secrets" },
{ scenario: "My parole officer said I need to stop _____. I disagree.", category: "Legal Trouble" },
{ scenario: "What's the difference between a politician and a _____ ? _____.", category: "Edgy Riddle" },
{ scenario: "The world's most offensive tattoo placement: _____ tattooed on _____.", category: "Pure Offensive" },
{ scenario: "My therapist says I use humor to mask _____. She's not wrong.", category: "Shrunk Talk" },
{ scenario: "What Genghis Khan and my ex have in common: _____.", category: "Dictator Comparisons" },
{ scenario: "The truth about what really happens in the Bermuda Triangle: _____.", category: "Conspiracy Theories" },
{ scenario: "The most offensive word in any language is _____ in _____.", category: "Pure Offensive" },
{ scenario: "My sexual awakening was accidentally caused by _____.", category: "Confessions" },
{ scenario: "The worst part of being a cannibal has to be _____.", category: "Too Dark" },
{ scenario: "The one thing they don't put on death row menus is _____.", category: "Too Dark" },
{ scenario: "What my search history reveals about me as a person: _____.", category: "Confessions" },
{ scenario: "The most disturbing clown-related incident in history was _____.", category: "Too Dark" },
{ scenario: "The thing Dracula does between victims that nobody talks about: _____.", category: "Supernatural Shenanigans" },
{ scenario: "My ex's new partner's most impressive quality, apparently, is _____.", category: "Ex-Files" },
{ scenario: "What the darkest corner of Reddit is currently discussing: _____.", category: "Internet Horrors" },
{ scenario: "The most unsettling Google autocomplete suggestion for '_____' is _____.", category: "Internet Horrors" },
{ scenario: "My prison pen pal keeps asking me to send _____.", category: "Legal Trouble" },
{ scenario: "The thing I would do if I was invisible for one day that I will never admit to: _____.", category: "Dark Confessions" },
{ scenario: "The rejected sequel to Schindler's List was called '_____.'", category: "Too Dark" },
{ scenario: "The most specific phobia I have developed from the internet is a fear of _____.", category: "Internet Horrors" },
{ scenario: "What two dictators would argue about if locked in a room together: _____.", category: "Dictator Comparisons" },
{ scenario: "My exorcist was baffled when the demon kept asking for _____.", category: "Supernatural Shenanigans" },
{ scenario: "The official cause of death on my inevitable autopsy report will read: '_____.'", category: "Dark Predictions" },
{ scenario: "The world's most offensive breakfast cereal is called _____ and the mascot is _____.", category: "Pure Offensive" },
{ scenario: "My spirit animal got one look at me and immediately filed for a different host.", category: "Self-Roast" },
{ scenario: "What I genuinely believe happens to you after you die: _____.", category: "Dark Predictions" },
{ scenario: "The most disturbing fortune cookie message ever received: '_____.'", category: "Dark Predictions" },
{ scenario: "The worst country to accidentally end up in while holding _____: _____.", category: "Travel Nightmares" },
{ scenario: "What my liver would say if it could talk: '_____.'", category: "Self-Roast" },
{ scenario: "The most offensive name for a strip club: '_____.'", category: "Pure Offensive" },
{ scenario: "My Tinder bio says I'm looking for someone who doesn't mind _____.", category: "Dating Disasters" },
{ scenario: "The worst diagnosis to receive right before a vacation: _____.", category: "Medical Mysteries" },
{ scenario: "What the world would look like if _____ had won WWII instead.", category: "Alternative History" },
{ scenario: "The most niche fetish ever documented by a psychologist was a deep attraction to _____.", category: "Spicy After Dark" },
{ scenario: "My horoscope said I should stop _____ but has it met me?", category: "Cosmic Regrets" },
{ scenario: "The world's darkest children's fairy tale ends with _____ dying because of _____.", category: "Too Dark" },
{ scenario: "The reason I'm on a government watchlist is almost certainly _____.", category: "Classified Secrets" },
{ scenario: "My necromancer can bring back one person from history and chose _____. Big mistake.", category: "Supernatural Shenanigans" },
{ scenario: "The most offensive theme for a gender reveal party: _____.", category: "Pure Offensive" },
{ scenario: "What the Devil actually does on his days off: _____.", category: "Supernatural Shenanigans" },
{ scenario: "The true reason I was banned from that country forever: _____.", category: "Legal Trouble" },
{ scenario: "My dealer's product descriptions are surprisingly poetic, especially for '_____.'", category: "Street Pharmacology" },
{ scenario: "What my shrink told her husband about me after our session: '_____.'", category: "Shrunk Talk" },
{ scenario: "The most offensive national monument that somehow got approved: _____.", category: "Pure Offensive" },
{ scenario: "What Saddam Hussein kept in his secret bathroom: _____.", category: "Dictator Fantasies" },
{ scenario: "The funniest way to be accidentally racist without knowing it: _____.", category: "Oops Racism" },
{ scenario: "The world's most disturbing side effect listed on antidepressants: _____.", category: "Medical Mysteries" },
{ scenario: "The worst name for a funeral home: '_____.'", category: "Too Dark" },
{ scenario: "What actually killed Marilyn Monroe, according to the file they won't release: _____.", category: "Conspiracy Theories" },
{ scenario: "My ghost will haunt people by doing nothing but _____ for eternity.", category: "Dark Predictions" },
{ scenario: "The most disturbing thing about competitive hotdog eating: _____.", category: "Dark Observations" },
{ scenario: "What the world's last cannibal was caught trying to season his food with: _____.", category: "Too Dark" },
{ scenario: "The dumbest way anyone has ever died, according to the coroner's report: _____.", category: "Too Dark" },
{ scenario: "The most regrettable thing I've ever said during sex: '_____.'", category: "Spicy After Dark" },
{ scenario: "The reason I'm currently banned from three countries is _____.", category: "Legal Trouble" },
{ scenario: "What they found in the walls of my Airbnb: _____.", category: "Travel Nightmares" },
{ scenario: "The world's worst name for a children's hospital ward: '_____.'", category: "Too Dark" },
{ scenario: "My exorcism failed because the demon kept saying _____.", category: "Supernatural Shenanigans" },
{ scenario: "The last thing I want on my tombstone is '_____', but knowing me, that's exactly what it'll say.", category: "Dark Predictions" },
{ scenario: "What the Grim Reaper listens to while working: _____.", category: "Too Dark" },
{ scenario: "The world's most disturbing trend in dating apps is people listing _____ as a hobby.", category: "Dating Disasters" },
{ scenario: "My mugshot caption in the paper would simply read: 'Man arrested for _____.'", category: "Legal Trouble" },
{ scenario: "The funniest accidental war crime: _____.", category: "Alternative History" },
{ scenario: "What happens inside a swingers club that nobody expects on their first visit: _____.", category: "Spicy After Dark" },
{ scenario: "The world's most suspicious missing persons case involves someone who was last seen _____.", category: "True Crime Lite" },
{ scenario: "My will specifically states that under no circumstances should anyone find _____.", category: "Dark Predictions" },
{ scenario: "The most offensive ice cream flavor name: _____.", category: "Pure Offensive" },
{ scenario: "What Hitler and my landlord have in common: _____.", category: "Dictator Comparisons" },
{ scenario: "The most disturbing thing to discover about your dentist: _____.", category: "Medical Mysteries" },
{ scenario: "The leaked government document simply titled '_____' caused an international incident.", category: "Classified Secrets" },
{ scenario: "The most disturbing use of a taxidermied animal: _____.", category: "Too Dark" },
{ scenario: "My neighbor was arrested last week for _____, and honestly, I'm not surprised.", category: "Neighbor Nightmares" },
{ scenario: "What ancient Romans did for fun that we're lucky we can't Google images of: _____.", category: "Alternative History" },
{ scenario: "The saddest meal a person can eat: _____, alone, in _____.", category: "Dark Observations" },
{ scenario: "The worst airport to be stranded in while carrying _____: _____.", category: "Travel Nightmares" },
{ scenario: "The most offensive charity name: '_____.'", category: "Pure Offensive" },
{ scenario: "My dying wish is to be remembered for _____. Unfortunately, I'll be remembered for _____.", category: "Dark Predictions" },
{ scenario: "The most disturbing Yelp review ever written was for a _____ that offered _____.", category: "Too Dark" },
{ scenario: "What Vikings actually argued about around the campfire: _____.", category: "Alternative History" },
{ scenario: "The worst possible theme for an adult birthday party: _____.", category: "Party Fails" },
{ scenario: "My cult's initiation ritual involves _____ and a waiver you can't Google.", category: "Supernatural Shenanigans" },
{ scenario: "The most offensive name for a gym: '_____.'", category: "Pure Offensive" },
{ scenario: "What the last thing a hitman said to his target was: '_____.'", category: "Too Dark" },
{ scenario: "The world's most disturbing talent show act involved someone who could _____.", category: "Too Dark" },
{ scenario: "My drug test came back positive for _____, which I cannot explain.", category: "Legal Trouble" },
{ scenario: "The forbidden section of the library contains nothing but books about _____.", category: "Classified Secrets" },
{ scenario: "The most disturbing thing about living next to a cemetery: _____.", category: "Home Horrors" },
{ scenario: "My dealer gave me a customer loyalty card. After ten stamps I get _____.", category: "Street Pharmacology" },
{ scenario: "The worst thing to accidentally say to a therapist on your first appointment: '_____.'", category: "Shrunk Talk" },
{ scenario: "What Stalin's bedtime routine looked like: _____.", category: "Dictator Fantasies" },
{ scenario: "The most disturbing item ever found at a garage sale: _____.", category: "Home Horrors" },
{ scenario: "The funniest cause of a historical war: _____.", category: "Alternative History" },
{ scenario: "My most questionable eBay purchase arrived in a box labeled '_____.'", category: "Internet Horrors" },
{ scenario: "What Genghis Khan's Tinder bio would say: '_____.'", category: "Dictator Comparisons" },
{ scenario: "The world's most uncomfortable family road trip game: _____.", category: "Family Secrets" },
{ scenario: "What the coroner put as 'manner of death' on the world's most embarrassing autopsy: _____.", category: "Too Dark" },
{ scenario: "My parole conditions specifically prohibit me from _____.", category: "Legal Trouble" },
{ scenario: "The most disturbing episode of a children's cartoon that was never released: '_____.'", category: "Too Dark" },
{ scenario: "The one thing my therapist said that I still don't think I'm ready to unpack: '_____.'", category: "Shrunk Talk" },
{ scenario: "What the Deep Web's most visited website is actually about: _____.", category: "Internet Horrors" },
{ scenario: "The most offensive name for a daycare center: '_____.'", category: "Pure Offensive" },
{ scenario: "My Fitbit registered _____ during what I told it was a 'walk.'", category: "Spicy After Dark" },
{ scenario: "The most disturbing use of a ventriloquist dummy: _____.", category: "Too Dark" },
{ scenario: "The funniest reason to be deported from a country: _____.", category: "Legal Trouble" },
{ scenario: "What Mussolini kept under his bed: _____.", category: "Dictator Fantasies" },
{ scenario: "The most disturbing thing to find in a secondhand book: _____.", category: "Home Horrors" },
{ scenario: "My new OnlyFans niche is _____ and the market is surprisingly strong.", category: "Spicy After Dark" },
{ scenario: "The world's worst name for a pharmacy: '_____.'", category: "Pure Offensive" },
{ scenario: "What my probation officer pretends not to notice: _____.", category: "Legal Trouble" },
{ scenario: "The most offensive street name in any city: '_____.'", category: "Pure Offensive" },
{ scenario: "My therapist said I need to work on my relationship with _____. She was referring to _____.", category: "Shrunk Talk" },
{ scenario: "The most disturbing thing about the dark web is that it has a dedicated section for _____.", category: "Internet Horrors" },
{ scenario: "What happens at furry conventions that they absolutely do not advertise: _____.", category: "Spicy After Dark" },
{ scenario: "The deleted scene from a Disney movie that would have traumatized a generation: _____.", category: "Too Dark" },
{ scenario: "The most disturbing national dish of any country: _____.", category: "Foodie Fails" },
{ scenario: "What I'm legally not allowed to say about my ex: _____.", category: "Legal Trouble" },
{ scenario: "The worst advice I got from a conspiracy theorist that I actually followed: _____.", category: "Conspiracy Theories" },
{ scenario: "The most disturbing thing about competitive bodybuilding is _____.", category: "Dark Observations" },
{ scenario: "My therapist's personal notes on me include the phrase '_____' circled three times.", category: "Shrunk Talk" },
{ scenario: "The most offensive superhero power imaginable: _____.", category: "Pure Offensive" },
{ scenario: "What the world's worst detective solved as his finest case: _____.", category: "True Crime Lite" },
{ scenario: "The most disturbing thing about a mime's personal life: _____.", category: "Too Dark" },
{ scenario: "My dealer described the new batch as 'tasting like _____ with a hint of _____.'", category: "Street Pharmacology" },
{ scenario: "The thing that immediately ends a threesome: _____.", category: "Spicy After Dark" },
{ scenario: "The world's most disturbing use of a sock: _____.", category: "Too Dark" },
{ scenario: "What really happened at the Last Supper that wasn't in any scripture: _____.", category: "Alternative History" },
{ scenario: "The most disturbing thing I've found on my roommate's side of the room: _____.", category: "Roommate Hell" },
{ scenario: "The one item you should never pack when visiting North Korea: _____.", category: "Classified Secrets" },
{ scenario: "What the bail conditions for my ideal crime spree would include: _____.", category: "Legal Trouble" },
{ scenario: "The most cursed NFT ever minted was an image of _____.", category: "Internet Horrors" },
{ scenario: "Hitler's one regret, according to a fictional diary found in Argentina, was _____.", category: "Dictator Fantasies" },
{ scenario: "The worst possible thing to name a boat: '_____.'", category: "Bad Decisions" },
{ scenario: "My darkest Google search happened at 3 AM and was simply: '_____?'", category: "Internet Horrors" },
{ scenario: "The most offensive thing a wedding officiant has ever said mid-ceremony: '_____.'", category: "Wedding Chaos" },
{ scenario: "What the world's worst psychic predicted, accurately, about me: '_____.'", category: "Supernatural Shenanigans" },
{ scenario: "The rejected name for the atom bomb was '_____' and it was honestly funnier.", category: "Alternative History" },
{ scenario: "The most disturbing item in a survivalist's bug-out bag: _____.", category: "Survival Strategy" },
{ scenario: "My séance accidentally summoned _____ instead of a dead relative.", category: "Supernatural Shenanigans" },
{ scenario: "The worst text to accidentally send your dad: '_____.'", category: "Family Secrets" },
{ scenario: "The most disturbing thing to hear your doctor say while you're under anesthesia: '_____.'", category: "Medical Mysteries" },
{ scenario: "What I discovered about my grandfather after reading his war diary: _____.", category: "Family Secrets" },
{ scenario: "The most offensive job title a person can have: '_____.'", category: "Pure Offensive" },
{ scenario: "The world's most dangerous party game: _____.", category: "Party Fails" },
{ scenario: "The worst possible use of a time machine: _____.", category: "Dark Predictions" },
{ scenario: "The most disturbing item currently for sale on Etsy: _____.", category: "Internet Horrors" },
{ scenario: "My prison tattoo says _____ and I genuinely don't know what it means.", category: "Legal Trouble" },
{ scenario: "What Kim Jong-un does to relax on weekends: _____.", category: "Classified Secrets" },
{ scenario: "The worst possible name for a strip club in a small town: '_____.'", category: "Pure Offensive" },
{ scenario: "The most disturbing evidence found at a crime scene: _____.", category: "True Crime Lite" },
{ scenario: "My doctor told me to cut back on _____ and I immediately cut back on my doctor.", category: "Medical Mysteries" },
{ scenario: "The most offensive national flag redesign proposal ever submitted: _____.", category: "Pure Offensive" },
{ scenario: "What the world's worst assassin used as a weapon: _____.", category: "True Crime Lite" },
{ scenario: "The most disturbing thing stored in my browser's private tab: _____.", category: "Confessions" },
{ scenario: "My toxicology report will one day include both _____ and _____, and I have no regrets.", category: "Confessions" },
{ scenario: "The worst possible last words to say before jumping out of a plane: '_____.'", category: "Dark Predictions" },
{ scenario: "What a hitman lists under 'skills' on his LinkedIn: _____.", category: "True Crime Lite" },
{ scenario: "The most disturbing spa treatment imaginable: _____.", category: "Wellness Nonsense" },
{ scenario: "My cult's sacred text is basically just a pamphlet about _____.", category: "Supernatural Shenanigans" },
{ scenario: "The most disturbing thing found inside a pinata at a child's birthday party: _____.", category: "Too Dark" },
{ scenario: "What ancient Egyptians did on the weekends, according to the hieroglyphs they hid: _____.", category: "Alternative History" },
{ scenario: "The world's most troubling autocorrect replacement: _____ changed to _____.", category: "Tech Problems" },
{ scenario: "The worst thing about an open-casket funeral is when _____.", category: "Too Dark" },
{ scenario: "My drug dealer gives me a Christmas card every year that just says '_____.'", category: "Street Pharmacology" },
{ scenario: "The most disturbing use of a vacuum cleaner: _____.", category: "Too Dark" },
{ scenario: "What made the world's biggest scandal seem small by comparison: _____.", category: "Dark Observations" },
{ scenario: "The most disturbing thing to find in a hotel Bible: _____.", category: "Too Dark" },
{ scenario: "My spirit guide materialized, looked at my life, and immediately requested a transfer to _____.", category: "Self-Roast" },
{ scenario: "The worst thing to shout while being arrested: '_____.'", category: "Legal Trouble" },
{ scenario: "The most disturbing use of a garden gnome: _____.", category: "Home Horrors" },
{ scenario: "What Caligula's Yelp review of ancient Rome would say: '_____.'", category: "Alternative History" },
{ scenario: "The most offensive product name ever approved by a marketing team: '_____.'", category: "Pure Offensive" },
{ scenario: "My court-appointed therapist described me to the judge as '_____.'", category: "Legal Trouble" },
{ scenario: "The worst possible first tattoo location and design: _____ on the _____.", category: "Bad Decisions" },
{ scenario: "The most disturbing thing to put on a business card: _____.", category: "Pure Offensive" },
{ scenario: "My future biographer will spend an entire chapter explaining _____.", category: "Legacy Fails" },
{ scenario: "The most offensive wedding cake topper: _____.", category: "Wedding Chaos" },
{ scenario: "What archaeologists will find in my home in 500 years and deeply misunderstand: _____.", category: "Dark Predictions" },
{ scenario: "The most disturbing thing about clown school: _____.", category: "Too Dark" },
{ scenario: "My restraining order specifically mentions I cannot come within 100 meters of _____.", category: "Legal Trouble" },
{ scenario: "The most offensive name for a boat: '_____.'", category: "Pure Offensive" },
{ scenario: "The thing I did in Vegas that even Vegas can't keep quiet about: _____.", category: "Vegas Stories" },
{ scenario: "The most disturbing thing about taxidermy as a hobby: _____.", category: "Too Dark" },
{ scenario: "What was found in the walls of Buckingham Palace during renovations: _____.", category: "Classified Secrets" },
{ scenario: "The most offensive birthday card you can buy at a gas station: '_____.'", category: "Pure Offensive" },
{ scenario: "My one call from prison was to tell someone to hide _____.", category: "Legal Trouble" },
{ scenario: "The strangest item on my criminal record: '_____.'", category: "Legal Trouble" },
{ scenario: "The most disturbing thing to find growing in a public swimming pool: _____.", category: "Dark Observations" },
{ scenario: "What Nero was actually doing while Rome burned: _____.", category: "Alternative History" },
{ scenario: "The most offensive self-help book title ever published: '_____.'", category: "Pure Offensive" },
{ scenario: "My life insurance policy specifically excludes death by _____.", category: "Dark Predictions" },
{ scenario: "The worst possible name for a therapist's practice: '_____.'", category: "Pure Offensive" },
{ scenario: "What the police dog found in my car that I genuinely cannot explain: _____.", category: "Legal Trouble" },
{ scenario: "The most offensive thing to put on a gravestone: '_____.'", category: "Too Dark" },
{ scenario: "The most disturbing use of a leaf blower: _____.", category: "Too Dark" },
{ scenario: "My therapist's eyes went wide when I described my relationship with _____.", category: "Shrunk Talk" },
{ scenario: "The most offensive way to end a breakup: _____.", category: "Ex-Files" },
{ scenario: "What Stalin kept as a pet and why it disappeared: _____.", category: "Dictator Fantasies" },
{ scenario: "The most disturbing item in the world's best-selling IKEA collection: '_____.'", category: "Home Horrors" },
{ scenario: "The most inappropriate song to play at a funeral: '_____.'", category: "Too Dark" },
{ scenario: "My crime scene would confuse even the most experienced detective because of _____.", category: "True Crime Lite" },
{ scenario: "The most disturbing thing about being a professional food taster: _____.", category: "Dark Observations" },
{ scenario: "What the Devil offered me at the crossroads and why I said no: _____.", category: "Supernatural Shenanigans" },
{ scenario: "The most offensive thing ever printed on a motivational poster: '_____.'", category: "Pure Offensive" },
{ scenario: "My most recent Google search at 4 AM was '_____' and I regret nothing.", category: "Internet Horrors" },
{ scenario: "The most disturbing mascot for a children's fast food chain: _____.", category: "Too Dark" },
{ scenario: "What Hitler's Amazon wish list looked like in his final weeks: _____.", category: "Dictator Fantasies" },
{ scenario: "The most offensive country name if countries were named by the internet: '_____.'", category: "Pure Offensive" },
{ scenario: "My criminal defense attorney's opening argument was: 'Ladies and gentlemen, my client is guilty of many things, but not _____.'", category: "Legal Trouble" },
{ scenario: "The most disturbing chapter in any children's textbook: '_____.'", category: "Too Dark" },
{ scenario: "What the last living dinosaur was doing when the asteroid hit: _____.", category: "Alternative History" },
{ scenario: "The most offensive thing to say at a job interview: '_____.'", category: "Career Suicide" },
{ scenario: "My séance went wrong when the spirit kept asking us to _____ before it would leave.", category: "Supernatural Shenanigans" },
{ scenario: "The most disturbing ingredient in a witch's brew, other than the obvious: _____.", category: "Supernatural Shenanigans" },
{ scenario: "What Mao Zedong's Yelp profile would review first: _____.", category: "Dictator Comparisons" },
{ scenario: "The most offensive bumper sticker ever approved for sale: '_____.'", category: "Pure Offensive" },
{ scenario: "My suicide note will be mostly a rant about _____ with a small mention of _____.", category: "Dark Predictions" },
{ scenario: "The most disturbing thing about professional competitive eating: _____.", category: "Sports Disasters" },
{ scenario: "What God and my landlord have in common: _____.", category: "Dark Observations" },
{ scenario: "The most offensive name for a perfume: '_____.'", category: "Pure Offensive" },
{ scenario: "My toxicologist looked at my results and asked: 'How are you even standing?'", category: "Medical Mysteries" },
{ scenario: "The most disturbing thing to put in a time capsule: _____.", category: "Dark Predictions" },
{ scenario: "What Cleopatra's dating profile would say: '_____.'", category: "Alternative History" },
{ scenario: "The most offensive thing you can bring to a potluck: _____.", category: "Pure Offensive" },
{ scenario: "My last text before going off-grid was: '_____. Don't look for me.'", category: "Dark Predictions" },
{ scenario: "The most disturbing thing to find in a will: _____.", category: "Family Secrets" },
{ scenario: "What the world's worst surgeon said right before making the first incision: '_____.'", category: "Medical Mysteries" },
{ scenario: "The most offensive name for a bar: '_____.'", category: "Pure Offensive" },
{ scenario: "My witness protection new identity is _____ and my cover story is that I sell _____.", category: "True Crime Lite" },
{ scenario: "The most disturbing use of a children's toy: _____.", category: "Too Dark" },
{ scenario: "What the world's most prolific serial killer kept as a souvenir: _____.", category: "True Crime Lite" },
{ scenario: "The most offensive way to answer the phone professionally: '_____.'", category: "Pure Offensive" },
{ scenario: "The saddest thing about being a villain is _____.", category: "Dark Observations" },
{ scenario: "What my dealer said when I asked for something 'stronger': '_____.'", category: "Street Pharmacology" },
 
  
];
